- music_assistant/providers/file/__init__.py
The disc and track numbers are often stored as strings containing e.g.
"1/16" which leads to exceptions.
Also taglib sometimes returns empty lists which also produces an
exception.
This fix avoids some common exceptions.
> Fix tag reading exceptions

- music_assistant/controllers/stream.py
leftover after recent settings refactor
> Fix attribute error crossfade_duration

- music_assistant/helpers/database.py
bug in database code caused the music library being fully rescanned at every start
> Fix music library being recreated at every start

- music_assistant/controllers/music/__init__.py
when invalid uri was passed the exception that was thrown was a bit meaningless.
This should make it more clear
> Improve uri parse helper to give better exception if it fails

- music_assistant/controllers/stream.py
Use static buffer of 1 second to prevent lag at start of stream.
Effectively this disables crossfade support but that is not of interest for a radio stream
> Decrease buffer for radio playback

- music_assistant/controllers/stream.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/process.py
Due to a race condition a BrokenPipe error may be raised when streaming is aborted (or user skips to the next track).
This should be fixed with this changes.
> Fix BrokenPipe Error when streaming is aborted

- requirements.txt
We're using features only available in the latest version
> Pin aiofiles to 0.8.0

- music_assistant/controllers/stream.py
- music_assistant/models/player_queue.py
- Make sure that a player should stop playback when we have no more tracks in queue.
- Do not repeat the queue's last track when the queue is at the end (and repeat disabled)
> Fix: Stop playback at end of queue properly

- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/models/config.py
- music_assistant/models/provider.py
Fixes the (race) condition where an artist exists on both disk (file provider) and a streaming provider with an endresult that the artist did not get marked as "in library" (which is a global preference of a media item, regardless of how many providers).
This forces the media item as in library from the filesystem scan and it has a guard on the streaming provider sync to not remove an item from the library if there are other providers attached to the same provider.
> Fix artist not marked as 'in library' when exists on multiple providers

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/controllers/music/providers/qobuz.py
- music_assistant/controllers/music/providers/spotify.py
- music_assistant/helpers/database.py
- music_assistant/models/media_items.py
- Enable support that an album can have multiple artists
- Including backwards compatibility
- Including database migration
- No rescan of existing media, a simple "refresh" on an album will reveal the additional artist(s)
> Support for album having multiple artists

- music_assistant/models/player_queue.py
- clear current item when player finishes  playing last item in the queue
- change index to 0 when repeat enabled on the whole queue
> Fix queue repeat issues

- music_assistant/models/player_queue.py
- music_assistant/models/queue_settings.py
Fix queue get corrupt when adding a single track while there is no track loaded (active) in the queue.
Bit of an edge case but still good to fix.
> Fix queue corruption issue

- music_assistant/models/media_items.py
Use album image by default if the track has no image itself
> Fix default album fallback image for tracks

- examples/full.py
- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/metadata/audiodb.py
- music_assistant/controllers/metadata/musicbrainz.py
- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/cache.py
- music_assistant/helpers/compare.py
- music_assistant/helpers/database.py
- music_assistant/helpers/images.py
- music_assistant/helpers/process.py
- music_assistant/helpers/tags.py
- music_assistant/helpers/util.py
- music_assistant/mass.py
- music_assistant/models/enums.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
- music_assistant/models/music_provider.py
- music_assistant/models/queue_settings.py
- music_assistant/music_providers/filesystem.py
- music_assistant/music_providers/qobuz.py
- music_assistant/music_providers/tunein.py
- requirements.txt
- switch to ffmpeg for all tag parsing
- read all available tags from files
- support for more filetypes (e.g. dsf)
- fix musicbrainz lookups
- fix database lockups
BREAKING CHANGE: filesystem provider items are not longer favorited by default
> Fix mapping and database issues

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- Allow for more realtime streaming
- Prevent delays when sending short audio clips (e.g. announcements)
- Fix delay when streaming YT music
This makes the audio buffer a bit more smart. At track start it will yield chunks of 100ms as soon as possible.
Further down the track it will try to buffer 16 seconds of audio if the bandwidth allows, more if possible.
> Fix audio buffer issues

- music_assistant/music_providers/ytmusic/ytmusic.py
Youtube Music returns Various Artists as artist object without an id. Account for that
> Youtube Music: Fix artist missing on compilation albums

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/process.py
- music_assistant/music_providers/spotify.py
For example cast players (especially with Hires audio) want to buffer ahead, allow this without breaking the scenario where the audio source itself is throttled (streaming providers like YT Music)
> Allow more aggressive buffering by players that require it

- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/music/__init__.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/images.py
- music_assistant/helpers/tags.py
- music_assistant/helpers/uri.py
- music_assistant/models/enums.py
- music_assistant/models/music_provider.py
- music_assistant/models/player_queue.py
- music_assistant/models/queue_item.py
- music_assistant/music_providers/filesystem.py
- music_assistant/music_providers/url.py
Make the URL Music provider a first class citizen.
- Grab metadata if a plain url (or file) is passed to play_media
- Determine if URL is a Track or Radio stream
- Allow URL's in local playlists
> Extend support for plain URL's

- music_assistant/controllers/streams.py
- Only allow ICY metadata on mp3 streamtype
- Use default metaint of 8192 bytes
> Only allow ICY metadata on mp3 streamtype

- music_assistant/helpers/audio.py
- music_assistant/helpers/playlists.py
- music_assistant/music_providers/tunein.py
- music_assistant/music_providers/url.py
Some radio streams do not provide a stream directly but use an intermediate playlist (m3u or pls).
Added a few helpers to parse such playlists so that playback now works
> Fix for radio streams with playlist url

- music_assistant/music_providers/ytmusic/helpers.py
- music_assistant/music_providers/ytmusic/ytmusic.py
Adds support for Youtube brand accounts as request in [#658](https://github.com/music-assistant/hass-music-assistant/discussions/658)
> Add support for brand accounts

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- music_assistant/models/enums.py
- music_assistant/models/queue_settings.py
- Allow override of ICY metadata settings
- Calculate player buffer to skip crossfade buffer if not enough data
- Prevents hiccups with YT Music at start of queue streeam when the data is still throttled
> Buffer optimizations

- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/tracks.py
- music_assistant/controllers/players.py
- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- music_assistant/mass.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
- music_assistant/models/music_provider.py
- music_assistant/models/player.py
- music_assistant/models/player_queue.py
- music_assistant/models/queue_item.py
- music_assistant/music_providers/filesystem.py
- music_assistant/music_providers/spotify.py
* fix edge case where playlist track has invalid albumdetails
* make the audio buffer more dynamic
* fix loop thread safety (fixes issues with cast speakers)
* simplify some code
* simplify player poll task
* extend timeout for spotify token retrieval
* Fix count of PagedItems queries
* Fix relative paths in playlists
* Handle some edge cases in cleanup procedure
* Fix metadata checksum overwrite
* Fix type of mediaitem image
* additional guards for library edit usage
* Fix local artwork retrieval in artist/album folders
* Handle (and log) slow Spotify connection
> Various small fixes and enhancements

- music_assistant/controllers/media/playlists.py
- music_assistant/controllers/media/radio.py
prevent too many suggestions of one genre/style if the radio playlist contains a mix of multiple genres/styles.
this approach takes 5 suggestions from 1 track out of another 5 source tracks.
so the mix will still be 50/50 for original and suggested tracks but iterated in pairs of 5 instead of loading like 25 suggestions from 1 source track
> Improve Radio feature for mixed playlists

- music_assistant/controllers/media/artists.py
- music_assistant/controllers/metadata/metadata.py
- music_assistant/models/enums.py
- music_assistant/models/player_queue.py
Refactor Play media and queuing of items to support more flexible usecases.
- Radio mode is now a parameter instead of QueueOption
- Added "replace next" QueueOption to support keeping current index while changing all next items.
- Better shuffling of items
> Make Play media more flexible

- music_assistant/helpers/compare.py
loosen up the matching on name a small bit by ignoring diacritic characters. as additional safety guard the total difference of characters may not be more than 2
> Fix: Ignore diacritic characters when matching on name

- music_assistant/helpers/audio.py
- music_assistant/models/enums.py
closes https://github.com/music-assistant/hass-music-assistant/issues/791
> Fix support for mpeg dash based radio streams

- music_assistant/common/models/player.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/players.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/filesystem_local/manifest.json
- music_assistant/server/providers/filesystem_smb/manifest.json
- music_assistant/server/providers/slimproto/manifest.json
- music_assistant/server/providers/sonos/__init__.py
- Disable SONOS players by default in DLNA provider (to prevent duplicates)
- Do not initialize disabled players
- Handle disabled/unavailable players in a more elegant way
- Fix for Chromecast players turning on unsollicited
- Fix for double encrypted passwords
- Fix playlist thumb generation causing an endless loop
> Small follow up fixes

- music_assistant/common/helpers/util.py
- music_assistant/common/models/media_items.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/filesystem_smb/helpers.py
- music_assistant/server/providers/filesystem_smb/manifest.json
Create a single connection per action. This a bit slower but much more reliable.
Now it seems to handle all test cases I throw at it just fine.
Also adjust the configuration a bit and split out the path into server/host, share and subfolder
> Fix SMB Music provider

- music_assistant/server/controllers/config.py
Adding a new provider caused a keyerror on fresh installs
> Fix for adding new provider

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/players.py
- music_assistant/server/helpers/images.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/filesystem_local/base.py
Refactors the logic to resolve images that are not (or may be not) remotely accessible. Instead of limiting that functionality to the file providers, this is now useable for other providers too (e.g. Plex)
> Refactor image handling a bit

- music_assistant/server/controllers/player_queues.py
This PR ensures that the entire queue is shuffled when e.g. a new album is added to the queue and shuffle is enabled.
[Related backlog item](https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=24094419)
> Fix shuffle not shuffling entire queue

- music_assistant/server/providers/plex/__init__.py
To ensure that the correct provider is selected if multiple providers for different plex servers are configured, we use the instance_id instead of the domain as provider
> Use instance_id instead of domain, if the provider is requested

- music_assistant/server/providers/plex/__init__.py
By now it was possible that content type in tracks was set to None. If this is the case, this could cause an exception in the library sync
> Plex - Ensure content type is never None

- music_assistant/server/providers/plex/__init__.py
On connect all known addresses of the server are tried out and afterwards the best one (SSL over non SSL and local over remote) is used. The current timeout sometimes takes longer than the MA timeout of 30 seconds for the setup of a provider
> Plex - Set a timeout of 10 seconds to connect to the server

- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/providers/ytmusic/__init__.py
This PR:
- Adds ItemMappings to YTM
- Fixes nested resolving of ItemMappings
> Add item mappings to YTM

- music_assistant/server/providers/airplay/__init__.py
There is a RaopBridge binary for aarch64 but aarch64 was not an accepted architecture.
> Allow aarch64 architecture

- music_assistant/server/providers/plex/__init__.py
Even if the track's artist is different from the album's artist, we were only using the album's artist by now. This changes with this PR. Now we will be use the track's artist for tracks if it is different from the album's artist. As plex does not create artists in their database, if they don't have any albums, we have to create fake/MA-database-only artists on our side.
> Add Plex Track Artist for compilations

- music_assistant/server/providers/tidal/__init__.py
The image retrieval was not resolving the urls correctly, and was causing exceptions even when an image was available.
This was somehow caused by the asyncio.to_thread() raising the error "TypeError: 'str' object is not callable"
The other issue was that the I was initialisng a url with "None" and setting this onto an image metadata object as the url, when none was available, which due to the above error was always
> Fix tidal image retrieval

- music_assistant/server/providers/plex/helpers.py
By now we tried to connect to any resource. A resource can also be a PlexClient (e.g. a player/app etc.), so this can lead to multiple different problems and errors, as these devices do not have any libraries or something like that.
> Plex provider: Ensure that we only connect to servers

- music_assistant/server/providers/ytmusic/__init__.py
This PR disables caching of ciphers to prevent weird playback errors. It also adds some extra debugging to catch edge cases related to streaming.
> Disable Youtube Music cipher caching

- music_assistant/server/helpers/audio.py
This PR adds some more debug logging to `audio.py` so we can catch that weird `MediaNotFoundError`.
> Add debug logging to audio.py

- music_assistant/server/providers/plex/__init__.py
Finally the chapters are now available in the plexapi library 🥳
> Add chapters for plex audio books

- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/webserver.py
When running the server as HA add-on, add an option to expose the default webserver on the internal network
> Add option to expose the webserver port on HAOS config

- music_assistant/server/controllers/streams.py
Send larger chunks by default should solve some buffering issues on some playertypes.
> Increase chunksize for audio streams

- music_assistant/__main__.py
- music_assistant/server/server.py
Some mysterious issues we have atm might be caused by uvloop.
Disable it by default for now and make it a startup/config option to enable it.
> Do not load uvloop by default

- music_assistant/common/helpers/util.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/musicbrainz/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
Prevent duplicate filesystem mappings (as good as possible) by accounting for common typos and case insensitive matching
> Prevent duplicate filesystem mappings

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/url/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
Prevent our global models to be initialized by positional arguments only as that introduces hard to catch errors whenever the model changed.
> Make all models initializable by kwargs only

- music_assistant/server/providers/tidal/__init__.py
When going to album details from global search, there is a TypeError raised. Even though the Tidal API claims to return strings for IDs, the parsed IDs are in fact of type int. Adding an `str()`cast to all parsers in Tidal Provider
> Fix class mismatch

- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/deezer/gw_client.py
With this PR we log the listened songs on Deezer. This way, they also appear in the last played songs on Deezer if we play them in MA. We don't know for sure, how these data are used by Deezer, but it's our expectation that these logs have impact on the user's Flow and other auto-generated Playlists as well as on the compensation artists receive from Deezer.
> Deezer log listened songs

- README.md
Include a mount for the data store in the `docker run` command so that data persists between updates, and an explanatory note below. 
Could also just have the note and not include the `-v ...` but I feel this is an important thing to include since missing it out means data loss - potentially a lot of time wasted and users lost if someone sets up their entire library, setup etc first time, then updates and loses everything.
> Readme: Add data directory mount to docker run command and explanatory note

- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/plex/helpers.py
Due to config values being altered, this is a breaking change.
Remove and re-add plex provider
Added idx and enumeration to get_album_tracks function to avoid the `None`or `0` track number issue
We should do a follow up PR to remove this assert in albums.py. I don't have time right now to ensure all providers uphold this contract.
> FIx cumbersome restart, add idx to album tracks

- music_assistant/server/controllers/players.py
Originally raised here https://github.com/music-assistant/hass-music-assistant/issues/1504
The suggested fix however would result in child volumes not going below 1. Looking at the current behavior the use of average of the powered child volumes for the group is good however the percentage change gives rise to unexpected results. Apart fro the zero case I also tried setting one speaker to 46 and another to 10 which gave a group volume of 28. Changing the group volume to 56 resulted in the first player going to 98 and the other to 14. I don't think this is expected. Therefore this PR suggests changing to relative movement. With the player volumes limited to 0 and 100 I think the result should be OK but I haven't tested it to see what the UX is like.
> Fix child players get stuck on zero volume 

- music_assistant/server/providers/airplay/__init__.py
- fix white noise after pcm limit reached
- fix saving config values
- better handle of player removals
> Fix some issues with Airplay provider

- music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
This PR fixes the error that occurs when attempting to start a radio for a given soundcloud track.
https://github.com/music-assistant/server/blob/ea1143408ef90637ae3508ee55905f78dbf87834/music_assistant/server/providers/soundcloud/__init__.py#L269
The caller specifies the `limit` parameter, but the underlying function doesn't accept it, causing the code to panic and crash.
The `limit` parameter isn't used for now, but it seems better to include it in the `get_recommended` function (to align with the other methods in the same class), rather than remove the parameter from the call site.
> [soundcloud] bug fix: add limit parameter to get_recommended function

- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
The soundcloud integration only loads the first 50 tracks from the user's list after setup. This is primarily due to the default limit imposed on the underlying API functionality:
https://github.com/music-assistant/server/blob/7b08dcf9e5d82884ee4500b6e4b8056d00c19229/music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py#L121
For users with more than 50 liked tracks, this results in an incomplete import of such tracks into the Music Assistant.
We convert the soundcloud API library into an async generator, rather than a standard API fetcher. Pagination is implemented, and the `limit` parameter is made optional so that all tracks can be fetched if no limit is specified.
This was manually tested with an explicit limit, as well as without.
> [soundcloud] improved track iteration

- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/soundcloud/manifest.json
- music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
Similar to https://github.com/music-assistant/server/pull/922, the playlist import process is incomplete. Through trial and error, I discovered that soundcloud returns all forms of "track lists" as a response to the API call -- and that it was sorted by recency (which explained the behavior I witnessed on `2023.6.0b6`.
This PR fixes it right up. It generalizes soundcloud pagination for easier future adoption and for the soundcloud playlists.
Also, as requested, I added myself to the manifest (in alphabetical order).
Manually tested the `asyncsoundcloudpy` API.
> [soundcloud] Improved playlist iteration

- music_assistant/server/providers/slimproto/cli.py
This PR fix the Home Assistant squeezebox integration players discovery, by providing a valid start_index when receiving the command "player: status".
In this case, start_index was set to "status".
> fix: handle invalid start_index when receiving command player status

- music_assistant/server/providers/theaudiodb/__init__.py
Initially, adb_track was initialized to None but not assigned anywhere in the function but called by self.__parse_track(adb_track) causing systematically an error. Just removed adb_track and replaced it by item referencing the matched item content
> Fixed theaudiodb provider with get_track_metadata issue

- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/plex/helpers.py
- music_assistant/server/providers/plex/manifest.json
- requirements_all.txt
I labelled it as breaking change as users will definitely need to start over to ensure a smooth transition.
However, I don't see this as an issue, as I guess for most people it seems to not work at all at the moment.
The myplexaccount.ping() function seems to be all that is required for the refresh of the token
https://github.com/pkkid/python-plexapi/pull/1271
> Fixes for plex connection

- music_assistant/server/providers/opensubsonic/sonic_provider.py
The first commit addresses the way Navidrome handles Various Artists. Navidrome seems to accept having artists listed on tracks that are not in their database. This means that the entry is just a string name and not an ID for retrieving more information. We will handle this by using a dummy 'Unknown' artist when this occurs.
The second commit checks if we need to buile MediaItemImage objects. The provider was building MediaItemImage objects on the assumption that cover_id was a required field. However, this field is allowed to be empty. Check that the field exists before we build objects for the images.
> Subsonic: Handle missing artist id and check before building Images

- music_assistant/client/players.py
- music_assistant/server/controllers/player_queues.py
Add some config options to specify fallback/defaults to enqueue items.
> Add default enqueue options

- music_assistant/server/providers/opensubsonic/sonic_provider.py
The first commit should fix the multiple scrobble issue we were seeing by using the StreamDetails object callback to report playback completion instead of scrobbling in get_audio_stream.
The second commit handles track enumeration more intelligently by paginating the requests instead of making one giant call.
> Subsonic: Better scrobbling and track enumeration

- music_assistant/server/providers/opensubsonic/sonic_provider.py
Older Navidrome servers do not handle an empty query string and require the query to be "" when we want to enumerate all entries in a category. If the first try to query with an empty string fails, change to "".
> Subsonic: Support track enumeration on older Navidrome servers

- music_assistant/server/providers/opensubsonic/sonic_provider.py
We had all the code inplace except for a return statement. Make resolve_image() actually return the image bytes.
> Subsonic: fix cover art resolution

- music_assistant/server/controllers/player_queues.py
- music_assistant/server/providers/airplay/__init__.py
- Prevent race condition on streamreader when stopping raop streamer
- Handle prevent playback for airplay players
- enforce auth for airport express
- ensure player is powered before considering queue active
> Some small bugfixes and enhancements

- music_assistant/common/helpers/util.py
Looking up of free ports should be done on the global interface (0.0.0.0) for best compatibility. For example the stream server binds to a public interface, not 127.0.0.1, yet the port check is currently using 127.0.0.1.
This gives incorrect results in some cases. For example I have a thing bound to a specific interface on port 8096, but not on 127.0.0.1, so the current implementation thinks that 8096 is free, while in reality it is not.
I suggest using 0.0.0.0 instead of the default ip, because this port is dynamic anyway and we better find one that is not used on any other interface. This will mean no other service on the system needs this port. Otherwise collisions might happen in the future if another service tries to switch interfaces and ends up trying the one MA is bound to.
> Correctly select a free port

- music_assistant/server/providers/opensubsonic/sonic_provider.py
If this support is present, then we can seek using the stream endpoint timeOffset argument. If not we need to fall back to having the player provider do it.
> Subsonic: Check for transcodeOffset support on startup

- music_assistant/server/providers/opensubsonic/sonic_provider.py
We were using blocking IO directly in handle_async_init(), make this call use a task instead.
> Subsonic: Moving blocking IO to task

- .gitignore
- music_assistant/client/players.py
- music_assistant/common/helpers/global_cache.py
- music_assistant/common/helpers/uri.py
- music_assistant/common/helpers/util.py
- music_assistant/common/models/enums.py
- music_assistant/common/models/player.py
- music_assistant/common/models/player_queue.py
- music_assistant/common/models/queue_item.py
- music_assistant/common/models/streamdetails.py
- music_assistant/constants.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/fully_kiosk/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
Full support of the announce feature:
- If music playing it will be temporary interrupted and restored after the announcement
- will power on the player if needed and off if needed afterwards
- increases the volume slightly while playing the announcement
- prefers native approaches where possible (for example on sonos)
- works with all players
- For TTS announcements, supports prepending it with a "pre announcement sound"
Requires new HA integration as well - breaking changes!
> Announce support (TTS with automatic resume)

- music_assistant/common/helpers/util.py
- music_assistant/server/helpers/process.py
- music_assistant/server/providers/snapcast/__init__.py
Our docker image has been updated to include the snapserver 0.27 by default.
The Snapcast provider will now use the built-in/included snapserver by default and allow the user to switch to an external server in the settings.
Including the snapserver allows us to do the next step which is a metadata script next to the fact that is way easier for users this way.
> Include a Snapserver in the snapcast provider

- music_assistant/server/providers/deezer/__init__.py
Fixes [this](https://github.com/music-assistant/hass-music-assistant/issues/1777) (maybe not in the best way - open to ideas).
Basically some Deezer tracks (I think the user-uploaded ones) don't have an `id` field in `artist`, e.g.:
```json
{
"id": -3092972371,
"readable": false,
"title": "1983 (Eric Prydz remix)",
"title_short": "1983 (Eric Prydz remix)",
"isrc": "",
"link": "https://www.deezer.com/track/-3092972371",
"duration": 720,
"rank": 0,
"explicit_lyrics": false,
"explicit_content_lyrics": 0,
"explicit_content_cover": 0,
"md5_image": "",
"time_add": 1706669513,
"artist": { "name": "Paolo Mojo", "tracklist": "", "type": "artist" },
"album": { "id": 0, "title": "1983", "md5_image": "", "tracklist": "", "type": "album" },
"type": "track"
}
```
There's a few options:
- Use the artist …
> Use Deezer artist name instead of ID when ID isn't present

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
Jellyfin's universal audio stream API will attempt to transcode any media to mp3 if the application does not specify what containers it supports [1].  If Music Assistant knows that the file in Jellyfin is of a certain container type, and thus expects an audio stream of that type, there may be a playback error when Jellyfin delivers the data in mp3 format instead.  This PR adds information about the containers supported by FFmpeg to the universal audio stream API call so that Jellyfin does not attempt to transcode unnecessarily.
[1] https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/UniversalAudioController.cs/#L269
> Jellyfin Transcoding Fix

- music_assistant/server/controllers/config.py
Small typo in the config controller.
It didn't cause any issues because os.path.join ignored the duplicate directory but stil good to fix.
closes https://github.com/music-assistant/hass-music-assistant/issues/2042
> Fix typo in config controller

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post-create.sh
- DEVELOPMENT.md
This adds support for Dev Containers/Codespaces to provide a supported development environment
> Add support for Dev Containers/Codespaces

- music_assistant/server/helpers/process.py
Long running (radio) streams caused the stderr buffer limit to be hit, waiting on a new line in the reader.
The result was a stalled or stopped radio stream.
This is now fixed by both extending the limit and catching this particular case.
> Prevent stderr pipe buffer overflow on long running radio streams

- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
I published deezer-python-async to pypi and switched the requirement to use that version instead.
> [Deezer]: Update deezer-python-async to use pypi version

- music_assistant/server/providers/ytmusic/__init__.py
Make sure to include videos in the search results as 'tracks'. This allows people to search for non-music content like desk concerts, kids music etc.
> Add videos to YTM search results

- music_assistant/server/controllers/music.py
Hey @marcelveldt , adding an item to favourites in MA is adding it to local library, but not to the Spotify library so I've taken a stab at a fix here - is this an acceptable fix?
I've seen bug reports and mentions of this from Spotify users, but from what I can tell this can't have worked for any provider, yet where are the bug reports?  So maybe I'm missing something...
> Ensure favorited item is added to provider library

- music_assistant/common/helpers/uri.py
- music_assistant/common/models/errors.py
- music_assistant/constants.py
- music_assistant/server/controllers/music.py
I often get Spotify URLs sent to me which I'd like to open directly in MA.  Right now I have to go into the Spotify app first to find out what it is, then search for the track in MA for playing.  It would be nice to use these URLs as is, so I've added support for using them in the MA global search.
Conversely I'd like to be able to copy the provider URL in MA so I can share it, but there's some CSS property making it unselectable and on a phone in portrait mode, the provider box contents wrap so the URL disappears, making it unclickable to go to Spotify app.  A button next to the URL to copy it to clipboard would be very nice!   Anyway that's a front end issue, so wrong place to put this I know ☺️ I'll put a feature request in for the new front end design.
Oh I've enabled the use of Qobuz …
> Add support for using streamer provider publicly shareable URLs in search query

- music_assistant/common/models/config_entries.py
- music_assistant/constants.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/webserver.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/helpers.py
- specify preferred metadata language on the metadata controller
- try to get the default setting (once) for the language from either the user's browser or a logged in streaming provider
- use the language on providers that support it (spotify and YTM)
Fixes https://github.com/music-assistant/hass-music-assistant/issues/751
> Add support to specify the Metadata language

- music_assistant/common/helpers/uri.py
- music_assistant/server/controllers/music.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/server.py
Make sure that all entries get cleaned up when removing a provider, even when the user decides to restart while a removal is in progress.
> Fix cleanup on removal of a provider

- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/deezer/gw_client.py
* don't use `seconds_skipped` from StreamDetails anymore
* avoid using `utc_now`
* use `cache_checksum` instead of `checksum` on MediaItemMetadata
> fix: Several minor fixes for deezer

- music_assistant/common/models/media_items.py
- music_assistant/constants.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/radio.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/providers/filesystem_local/base.py
- Fix images from local filesystem not detected in all conditions.
- Optimize database queries, reduce duplication/overhead.
- Fix several bugs in filesystem and library handling
- Fix: detect changes on filesystem files and write those to the library
> Library and filesystem providers optimizations

- music_assistant/server/controllers/music.py
- music_assistant/server/server.py
- don't start the webserver until all other core controllers are started
- bail out of starting the music controller if the database migration failed
- revert the previous database copy when migration failed
- log error when db migration failed
> Some fixes for Db migration and startup

- music_assistant/server/controllers/config.py
- music_assistant/server/providers/airplay/manifest.json
- music_assistant/server/providers/builtin/manifest.json
- music_assistant/server/providers/chromecast/manifest.json
- music_assistant/server/providers/dlna/manifest.json
- music_assistant/server/providers/fanarttv/manifest.json
- music_assistant/server/providers/musicbrainz/manifest.json
- music_assistant/server/providers/sonos/manifest.json
- music_assistant/server/providers/theaudiodb/manifest.json
- music_assistant/server/providers/ugp/manifest.json
- music_assistant/server/server.py
Partial fix for the fact that the Sonos provider makes the whole MA container crash on older systems.
With this PR we no longer load any provider by default anymore (except the builtin ones offcourse). 
Instead we are going to propose providers based on discovery and hints/getting started in the UI.
> Do not load any providers by default (except builtin)

- music_assistant/server/providers/opensubsonic/sonic_provider.py
The MediaImageItem construtor now requires a provider key word argument.
Previous versions of MA would avoid calling resolve_image if the path was None or empty. This seems to have changed and is causing errors in library syncing. The function now checks if path is empty and returns an empty list if so.
> Open Subsonic: Fix MediaImageItem constructor call

- music_assistant/common/models/enums.py
- music_assistant/common/models/media_items.py
Our calculation for scoring audio quality was not complete and didnt account for all situations.
For instance we got a report from someone using MP4 packed ALAC files being rated below Spotify's OGG.
This should fix that and handle a few other optimizations while at it.
> Fix the quality score

- music_assistant/server/controllers/player_queues.py
There were some typos in the default enqueue options parsing so this would fail on a fresh setup. 
This is now fixed (and the naming corrected)
> Fix default enqueue options

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
Turned out to be a stupid typo actually but well hidden ;-)
Fixes playlist items listings for user created playlists (on the mass provider) limited to 50 items.
> Fix mass user playlists (and queue items) limited to 50 items

- music_assistant/server/providers/musicbrainz/__init__.py
Do not use ISRC or barcode for lookups on MusicBrainz this info is incomplete and will lead to many useless calls, the strict MB id's or text searches are preferred. We were pointed to this after a chat with MusicBrainz discussing the many api calls from our project.
> Do not use ISRC or barcode for lookups on MusicBrainz

- music_assistant/server/providers/opensubsonic/sonic_provider.py
The standard for Open Subsonic is not complete for Songs so we don't know if this field will be supported. Once the standard is ready we can readress this.
Fixes: https://github.com/music-assistant/hass-music-assistant/issues/2247
> Subsonic: Set Track.disc_number to 0 for now

- music_assistant/server/providers/spotify/__init__.py
`_post_data` does return json from playlist ops so this is untouched.
> Fixes the spotify json decode mime-type errors

- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/snapcast/manifest.json
- requirements_all.txt
Fixes the following bug [https://github.com/music-assistant/hass-music-assistant/issues/2108](https://github.com/music-assistant/hass-music-assistant/issues/2108)
The repair involves changing the player_ids so there will remain old instances of snapclients
> Fix snapcast players ids

- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/tidal/__init__.py
This PR:
- Fixes parsing of public playlists that were added to the user's library
- Implements paging for obtaining playlist tracks
> Fix: apple music playlists

- music_assistant/common/models/errors.py
- music_assistant/server/providers/opensubsonic/sonic_provider.py
The first commit adds the ability to edit playlists from MA, partially addressing the feature request in https://github.com/orgs/music-assistant/discussions/2358 favorite syncing will come later.
The second commit explicitly sets the favorite field in the album and artists constructors to the value in the provider.
> Two updates to the Subsonic provider

- music_assistant/server/providers/jellyfin/__init__.py
AFAICT, https://github.com/music-assistant/server/pull/1325 introduced a regression in syncing Jellyfin tracks. After that merge the code started looking for ITEM_KEY_ALBUM_ID in the album metadata. It then tries to create an artist mapping with the ID of the album (rather than an artist id) and the "album artist" text from the album. This creates invalid data. Or it would, but an album doesn't actually have an AlbumId field at all.
This PR allows syncing to complete without exceptions again by using the "AlbumArtists" list from the album object:
```
"AlbumArtists": [
{
"Name": "Papa Roach",
"Id": "e439648e08ade14e27d5de48fa97c88e"
}
],
```
> Jellyfin: Fix regression importing track artist mapping

- music_assistant/server/providers/jellyfin/__init__.py
This is a follow up to https://github.com/music-assistant/server/pull/1332, and handles InvalidDataError in some other cases to ensure a Jellyfin sync does not fail entirely for a single bad file.
(I've not seen these ones in the wild, but there is the same lack of validation on the Jellyfin side so these seem worth adding).
> Jellyfin: Don't fail entire sync if a single track or album have an invalid mbid

- music_assistant/server/providers/snapcast/__init__.py
The method in the snapserver class does not call the callback, so the volume was not updated correctly. 
Also the muting logic is eliminated because it is not correct that if the volume of a group is changed, a muted client will sound again.
> Refactor SnapCastProvider cmd_volume_set method

- music_assistant/server/providers/snapcast/__init__.py
Introduces another bug, where only two clients can be synchronised.
> Revert "Fix snapcast player unsync when master off"

- music_assistant/server/providers/jellyfin/__init__.py
Just a tiny code cleanup I noticed.
> Jellyfin: Don't adjust logging level of unrelated providers dependencies

- music_assistant/server/controllers/config.py
- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/providers/hass/manifest.json
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/server.py
- requirements_all.txt
Currently, if a provider is unavailable at startup, it will never be retried. Also when the connection gets lost, there is no way to tell the server to retry later.
This PR addresses that:
- Implement auto retry logic if the initial load of a provider(instance) failed.
- Allow provider to reload itself (which is then also retried if that fails)
- Fix Home Assistant provider to reload when the connection was lost
- Fix Home Assistant provider for a player that is unavailable at startup but available later
> Auto retry provider load if its unavailable or the connection gets lost

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
Replacement library just implements the 7 or 8 API's the Jellyfin integration currently needs.
It deliberately tries to mirror the existing API, so that the switch can be reviewed more easily.
I think this fixes a few cases of calling blocking code on the event loop.
After it's merged I want to get mypy passing for the provider, and flush out the response schemas on the library side. I didn't want to make this change harder to review by doing that at the same time.
And i'll add a config bool for SSL verification (https://github.com/music-assistant/hass-music-assistant/issues/2025).
> Jellyfin: Drop all synchronous HTTP and use aiohttp instread

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
By passing `enableUserData` and `fields` to more requests we can get all the data we need from the `_search` methods without `_parse` methods needing to make additional HTTP requests. This can save hundreds if not thousands of HTTP requests on moderate libraries.
We are able to make _parse_playlist non-async as it already does no I/O, and _parse_album and _parse_artist are (after the change above) also I/O free. 
This just leaves _parse_track. I can easily get rid of 1 extra http request per track. However in the worst case, this function will still make 2 HTTP requests:
* If a track has `AlbumId` but not `Album` (the human readable album name) it does a HTTP request to get it for the ItemMapping
* If a track doesn't have `ArtistItems` but does have `AlbumId` it does a HTTP request to see …
> Jellyfin: Make less http requests

- music_assistant/server/controllers/music.py
The home screen of MA includes a 'recently added' row:
https://github.com/music-assistant/frontend/blob/7553714d748b53ba29b52671586ab38108fa18be/src/components/HomeWidgetRows.vue#L112
My library has ca. 8000s tracks and it takes a fair amount of time to fetch just that row (7-8s I think). This should speed up the fetch and hence the display of the home screen.
> Add index on timestamp_added

- music_assistant/server/providers/jellyfin/__init__.py
This lets you turn SSL verification on and off for Jellyfin. It is on by default (which technically might be a breaking change?). I don't know who would bother to set up SSL and then use a self signed cert these days, but as certificates were not validated before I thought I should leave in an escape hatch.
> Jellyfin: Make SSL verification optional, but on by default

- music_assistant/server/controllers/media/tracks.py
If you have the same track on two different albums via the filesystem provider, this code will force an overwrite of the album_tracks table, meaning it only gets shown on a single album, rather than (correctly) in both places.
AIUI the intention of the overwrite is to force rewriting in the case of modified ID3 tags, but the only tags that would be relevant in this case would be disc number and track number, and those should already be taken care of by this line:
https://github.com/music-assistant/server/blob/642ccbef85bd5a190078563e8572a5aa0dbc0e89/music_assistant/server/controllers/media/tracks.py#L453
Which does an insert or update as required.
See https://github.com/music-assistant/hass-music-assistant/issues/2506 for reporting of the issue.
> Prevent overwriting album_tracks table

- music_assistant/constants.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
This:
* Fixes a case where the same _parse_track call might call out to get the same album twice
* Fetches all tracks, even if they don't have an album
It also means instead of making a HTTP request for evey album its making one for every 4 or so albums (paginating over the whole library, rather than fetching each albums tracks).
Ideally i'd like to not query the album API at all when parsing the track. But:
* Right now we use the album to find the artist if the track doesn't have an artist directly. This feels weird and edge casey, but it does happen in my library.
* Apparently there might be edge cases where we have an album id but not name. Can I have an item mapping that has an id but not a name?
> Jellyfin: Faster track fetching

- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/snapcast/__init__.py
The method in the python-snapcast library requires that the sync and unsync be done in series and not in parallel.
Soon I will try to add a method that supports this option since the snapcast api allows these operations in a single call.
> Snapcast fix sync and unsync many

- music_assistant/server/controllers/media/playlists.py
Fix `ValueError: Sample larger than population or is negative` on playlists with less than 5 items.
> Fix radio for playlists < 5 items.

- music_assistant/server/providers/deezer/__init__.py
Playback from deezer gets possible again with this fix. Unfortunately the `skip_chunk` implementation caused that no chunks were decrypted anymore. The new logic is as follows:
If the current `chunk_index` is greater or equal to the `skip_chunk` value, we will yield the chunk. As we start with an index of 0 this should be the correct behavior - correct me if I am wrong, it has been a long week 😆 
Even if this is not the case, we increase the `chunk_index` and delete its bytes from the buffer. There is one exception from this rule: The first chunk is always used as it contains the audio file header. This is for sure no good solution, but at least for FLAC it's strictly necessary to have this header as ffmpeg won't play the content, if we don't provide it. I was also considering to extract …
> Deezer: Fix Playback

- music_assistant/server/providers/snapcast/__init__.py
A warning is displayed when deleting the provider, I forgot to change the cmd_stop code here in previous changes.
> Fix unload on snapcast

- music_assistant/server/helpers/audio.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
A few places were passing `str` to check_output rather then `list[str]`. The list is better - avoids needing to worry about escaping (for security), avoids a few fstrings, and avoids creating /bin/sh instances we don't need.
Hopefully fixes: https://github.com/music-assistant/hass-music-assistant/issues/2234 https://github.com/music-assistant/hass-music-assistant/issues/2266
> Avoid subshells when using check_output

- music_assistant/server/controllers/media/base.py
Additional logic got added to the compare_track function that accounts for ISRCs. When importing, it doesn't make it that far though. This is slightly clunky, but adding in an extra double check should handle it.
> Double check external ID comparison

- music_assistant/client/music.py
- music_assistant/common/helpers/datetime.py
- music_assistant/common/helpers/global_cache.py
- music_assistant/common/helpers/json.py
- music_assistant/common/helpers/uri.py
- music_assistant/common/helpers/util.py
- music_assistant/common/models/api.py
- music_assistant/common/models/config_entries.py
- music_assistant/common/models/enums.py
- music_assistant/common/models/errors.py
- music_assistant/common/models/media_items.py
- music_assistant/common/models/player.py
- music_assistant/common/models/player_queue.py
- music_assistant/common/models/provider.py
- music_assistant/common/models/queue_item.py
- music_assistant/server/providers/plex/__init__.py
- mypy.ini
I've added some comments where i'm a bit uncertain on this one.
> Mypy: Add music_assistant.common

- music_assistant/server/providers/snapcast/__init__.py
2000 ms seems to work fine, but I'm worried about a song with more than 2 seconds of silence in the middle.
[https://github.com/music-assistant/hass-music-assistant/issues/2402](https://github.com/music-assistant/hass-music-assistant/issues/2402)
> Snapcast: Add delay, before so that the stream does not idle immediately

- music_assistant/server/providers/opensubsonic/manifest.json
- requirements_all.txt
For a relaxation of the responses package version requirement.
> Bump py-opensonic to 5.1.1

- music_assistant/server/controllers/config.py
- music_assistant/server/server.py
Our retry logic never stops trying to load a provider until it works. Even after a provider is removed.
Because failures are captured with `self.config.set`, this causes corruption where we re-insert a nearly empty dict for an instance id:
```
"providers": {
"snapcast--e8gUtVPG": {
"last_error": "Unable to start the Snapserver connection ?"
}
}
```
This PR changes things to make sure a provider still exists in the config system before trying to load_provider. The corruption never happens, and the looping stops.
The problem with this approach is that it requires a ProviderConfig to be stored *before* we can call load_provider. This is a change in behaviour.
> Don't load_provider if provider already deleted

- music_assistant/server/providers/snapcast/__init__.py
I have found that sometimes the snapserver can crash, due to lack of ram I think. Use the connection down callback. Allow 1 try. if it fails restart the server.
> Snapcast: Reload built-in server in case of connection loss

- music_assistant/server/controllers/player_queues.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- Fix RadioBrowser browsing 
- Fix mounting SMB paths
- Fix Airplay playback
> Fix some bugs caused by regression

- music_assistant/server/controllers/config.py
- music_assistant/server/providers/snapcast/__init__.py
Another implementation for reloading snapcast when the connection to the server gets lost, which will work for both the builtin and external servers. It will also prevent a race condition when the connection drops
> Reload Snapcast provider when connection to the server gets lost

- music_assistant/server/helpers/process.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- Fix smb mount on MacOS
- Fix mount command if the username or password includes quotes
To handle special characters in the username and/or password, they need to be quoted correctly but the username/password can also contain quotes on its own, so our previous solution wasnt fail proof
Using environmental variables it works - it accepts all the special characters now
Only MacOS doesn't work but as that is dev only, we shouldn't care
> Better handle of SMB mount with special characters in username/password

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/config.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/dlna/helpers.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/fully_kiosk/__init__.py
- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/server.py
- Fix AlbumTrack parse from regular track
- Prevent lookups in non-existent folders
- Do not try to read ID3 tags from URL's with eyed3 
- Ignore volume DMCP request from apple devices
- Fix event handler for DLNA
- Fix saving more than 2 sample rates
- Enforce default mp3 codec on hass players
> A collection of small bugfixes and optimizations

- music_assistant/server/providers/opensubsonic/sonic_provider.py
We did not wrap the call to getArtist() in a try block and failures in that call are killing the provider. Add a wrapper that logs the failing ID and raises a MediaNotFoundError.
> Protect artist retrieval in Subsonic get_artist_toptracks()

- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/server.py
- Prevent that one failing provider aborts the other provider loads
- Fix Home Assistant Plugin load on supervisor installs
> Fix provider load at startup

- music_assistant/server/controllers/players.py
- music_assistant/server/helpers/multi_client_stream.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- music_assistant/server/server.py
For operations where we don't want to stop other tasks when one of the tasks fails we shouldn't use asyncio.TaskGroup
This PR introduces a small helper that can be used as context manager (like TaskGroup) but uses our builtin create_task logic to properly keep track of tasks and log unhandled exceptions.
This will at least guarantee that all tasks are executed where we don't want to abort the entire operation if one subtasks fails.
> Use TaskManager instead of TaskGroup

- music_assistant/server/providers/apple_music/__init__.py
Fix TypeError on creation of dummy albums (Introduced in https://github.com/music-assistant/server/pull/1463/)
@MarvinSchenkel See comment in https://github.com/music-assistant/hass-music-assistant/issues/2431
> apple_music: Fix creation of dummy albums

- music_assistant/server/providers/jellyfin/__init__.py
Somehow lost this in a merge or a rebase. If we don't specific the "extra" fields there's not enough data for _parse_track to work off.
> Fix Jellyfin similar tracks

- music_assistant/server/providers/jellyfin/__init__.py
Towards https://github.com/music-assistant/hass-music-assistant/issues/2594. It's not clear why this library has tracks with no MediaStreams - maybe API misuse on our part, maybe a corrupt library, maybe a setting. But lets log such tracks and allow the sync to continue.
> Jellyfin: Skip tracks with no MediaStreams

- music_assistant/server/providers/opensubsonic/sonic_provider.py
We are playing a little fast and loose with this UKNOWN_ARTIST_ID, it should never escape from the provider  code. The first patch here protects get_artist_toptracks() from sending this fake ID to the subsonic server. The second patch logs any time we find an album or track that ends up using UKNOWN_ARTIST.
> Subsonic: UNKNOWN_ARTIST handling

- music_assistant/client/music.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
Better differentiate the logic to get a media item with the logic to add an item to the library and/or refresh metadata.
Introduce a background scanner that very slowly checks for missing metadata (with only a limited amount of online calls allowed per day) which is better than refreshing the UI when you view it.
This fixes the various race conditions we've seen with continuous loops (also reported as wiggling UI)
> Refactor/cleanup the get/add logic for mediaitems + metadata retrieval

- music_assistant/server/providers/ytmusic/__init__.py
This PR refreshes the cache of YT DLP on startup to create authenticated requests, since the cache gets removed on reboot, causing the provider not to get loaded.
NB: I am planning to write my own yt dlp plugin that accept an access token to authenticate to yt dlp, rather than this 3rd party oauth plugin.
> YT Music: Fix token expiration on reboot

- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
This PR replaces the hacky ytdlp oauth plugin with my own plugin. Instead of having to abuse the yt dlp cache to pass an access token to the plugin, we can now pass the MA access token directly to be injected in the yt dlp requests.
> YTMusic: Rewrite YTM auth to ytdlp access token plugin

- music_assistant/server/providers/apple_music/__init__.py
100 is the max allowed, exceeding this limit results in a 400 error: https://github.com/music-assistant/hass-music-assistant/issues/2618
> Apple Music: Fix playlist page size for Apple music.

- music_assistant/server/controllers/metadata.py
Should fix:
```
2024-07-13 22:35:50.409 WARNING (MainThread) [music_assistant] Exception in task Task-607 - target: <coroutine object MetaDataController.metadata_scanner at 0x7fd1dc666460>: object async_generator can't be used in 'await' expression
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 274, in metadata_scanner
await self._update_playlist_metadata(playlist)
File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 580, in _update_playlist_metadata
playlist_items = await self.mass.music.playlists.tracks(playlist.item_id, playlist.provider)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object async_generator can't …
```
> iterate over async generator

- music_assistant/common/models/player_queue.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/builtin/__init__.py
Fix weird issue where multiple airplay streams get mangled together when they're started in quick succession. 
For example when resyncing or hitting the next button fast. Also guard a few other places that could use a bit of throttling/locking
> Fix AirPlay streams get mixed up when started in quick succession

- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tidal/helpers.py
This enables the long awaited PKCE login process, removes the "low 96 and low 320" quality options, and allows "full fat" streaming.
Adds all new config flow, with improved self documentation.
> Tidal PKCE login

- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
At some point I had switched to `/Items` instead of `/Artists` for consistency with every other object type and it seemed to work. However it was only returning a subset of artists. This reverts that, which restores full sync speed.
https://github.com/Jc2k/aiojellyfin/releases/tag/v0.9.2
> Jellyfin: Fix artist enumeration

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
- music_assistant/server/providers/jellyfin/manifest.json
- music_assistant/server/providers/jellyfin/parsers.py
- requirements_all.txt
- tests/server/providers/jellyfin/test_init.py
* The latest aiojellyfin uses the builder pattern. Mostly this is because the number of arguments the `/Items` API has is huuuge and my function bodies were getting ugly.
* Along with that, some of the fields become more strictly typed (so for example the `fields` query arg now has an enum instead of being text).
* Pagination moved out of MA and into the backing library, where its implemented once instead of 4 times. I also added a new prefetching strategy. It takes time to process a page of results and insert them in the MA db. On one of my older dev boxes that takes long enough that we can prefetch the next page.
(This isn't for backporting, though it could be after some time to brew up I guess).
> Jellyfin: Use aiojellyfin 0.10.0 for stricter typing and more speed

- music_assistant/server/providers/opensubsonic/sonic_provider.py
We need to try and debug why some M4A files are failing from certain providers and not others and some extra info is needed. Add debug level logging around stream start and end as well as when stream details are requested.
> Subsonic: Add debug level logging around stream start, end, and details

- music_assistant/server/providers/spotify/__init__.py
This tiny PR removes the `user-read-birthdate` scope which seems to be deprecated (see for instance https://github.com/jbszczepaniak/spotify-cli/pull/9). Spotify probably ignores it for old apps to avoid breaking them, but if a different client-id is used authentication fails unless `user-read-birthdate` is removed.
> Spotify: remove deprecated user-read-birthdate scope

- music_assistant/server/helpers/throttle_retry.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- pyproject.toml
- requirements_all.txt
This PR adds two improvements to throttling:
1. Accurate sleep until the next available time. `asyncio_throttle` by default wakes every 10msecs which is crazy. `ThrottlerManager` sets the wait to 100mecs, which is still unnecessary, but some modules don't use `ThrottlerManager` anyway.
2. Return the delay caused by the throttler (0 means no throttling) and log it in `throttle_with_retries`.
Since `asyncio_throttle` is very simple and looks unmaintained (PR ignored for years) I copied the code in `server/helpers/throttle_retry.py`, no point having an unmaintained dependency for a few lines of code.
> Throttler: sleep without busy wait, log delayed calls

- music_assistant/common/models/config_entries.py
- music_assistant/server/providers/spotify/__init__.py
Use a personal clientid for spotify to overcome the heavy rate limit limitation of our global clientid
> Allow use of a personal client id for Spotify

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/music.py
Prevent items get marked as unavailable during metadata scan is a provider is disabled by removing the logic that was in fact only needed for api clients to the serializing logic.
> Prevent items get marked as unavailable during metadata scan

- music_assistant/server/providers/filesystem_local/base.py
If the first time an artist is 'seen' is as an album artist, the sort_name is set into the cache first by the _parse_artist function, but that happens before the sort_name is added to the artist object from the tags. This should fix that.
> Ensure sort_name makes it to cache

- music_assistant/server/providers/ytmusic/__init__.py
Use a readable name for playlists that do not have a name (e.g. Likes) so the user can easily distinguish the playlist when multiple instances are configured.
> YTMusic: Use instance name as playlist owner as fallback.

- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/compare.py
- tests/server/test_compare.py
Fix a small oversight in the track linking logic that could result in a track being linked to an alternative version produced by another artist in some conditions.
> Fix issue with track linking

- music_assistant/server/providers/spotify/__init__.py
Spotify has phased out username+password login.
This PR switches to Spotify Connect authentication where you can use the mobile app to authenticate your account.
Note that we actually want to switch to a full (PKCE) oauth flow but librespot does not yet have support to pass the access token directly,
> Implement Spotify Connect Auth

- music_assistant/server/helpers/audio.py
Apple music relies on decryption keys being available in the `PlaylistItem`
> Apple Music: Fix condition for hls substream optimization.

- music_assistant/server/providers/opensubsonic/sonic_provider.py
This provider was using a mix of self.logger as well as creating it's
own outside the MA infrastructure. The correct thing to do is have the
provider log to self.logger so change all instances to that. This way
all provider logging respects the log level set either globally or for
this provider.
> Change logger used for provider

- music_assistant/server/providers/opensubsonic/__init__.py
This is moving to the core server, no need to do it in each provider.
> Remove the handle_async_init() call from provider __init__.py

- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/auth.py
- music_assistant/server/providers/spotify/__init__.py
By default we use the streamserver for auth callbacks but that is only available on the internal network.
We don't use the webserver because that could potentially be blocked behind a reverse proxy.
The downside of this is that you can't do any (re)auth (e.g. to spotify) when you are outside your home network, connected through HA ingress.
This PR allows the frontend to inform where its being called from so we can dynamically figure out the url for redirection.
This means that auth callbacks/popups should now also work through HA ingress or any other reverse proxy.
> Allow frontend to send base url for auth redirects

- music_assistant/server/controllers/media/base.py
Some leftover code was preventing provider removals to succeed
> Fix removal of a provider

- music_assistant/server/helpers/tags.py
In some cases, `eyed3` will return `None` instead of a file with empty tags. Fixes [issue #2793](https://github.com/music-assistant/hass-music-assistant/issues/2793).
> Guard against eyed3 returning None

- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
We weren't using the shared MA ClientSession for the login code. This meant login was hitting some extra YARL validation when instancing a ClientSession for a subpath on a url, causing logins to fail.
Hopefully fixes: https://github.com/music-assistant/hass-music-assistant/issues/2727
> Jellyfin: Fix login for some instances

- music_assistant/common/models/config_entries.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/ugp/__init__.py
Apparently some/all slimproto players do not even support HTTP 1.1 so chunked encoding fails.
This PR changes the default http profile to use streaming without content-length and without chunked encoding.
> Enforce default HTTP profile for slimproto players

- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
It seems that ffmpeg is really struggling with some continue HLS (radio) streams, especially the BBC. It just stops reading new chunks and aborts reading after one partial sublist finishes. 
This PR introduces our own HLS parser and streamer. It builts up onto the foundation we have added earlier but its focused on radio streams only. We let ffmpeg still deal with other HLS (and mpeg dash) streams.
Now let's see if this holds up better and streams keep running
> Introduce a HLS radio streams parser (for the BBC radio streams)

- .github/workflows/release.yml
- Dockerfile
Split the main pypi publish into 2 jobs with artifact upload/download
in-between. Added both jobs as dependencies to the release-notes and
addons update jobs, and made a start on a manually triggered dev build
with git hash as version tag
Added new build args with a MASS_INSTALL_LOCATION and DEV_RELEASE to
manipulate how and where the mass wheel is installed in the Dockerfile. Both have defaults that should cause the standard behaviour.
> Add dev manual build

- .github/workflows/release.yml
- Dockerfile
Add if always() to ensure further expression is checked, ensure that
build and push docker job runs after pypi publish is either successful
or skipped.  Move download artifacts job to after checkout so that it
isn't wiped out by the checkout
> fix: 🐛 move download to after checkout, fix conditionals

- music_assistant/common/models/streamdetails.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- Ensure that playback continues even when the streaming of a single track failed.
- Try to minimize the issue that spotify's token expires just when playback is requested
- Better logging of stream errors
- Move silence strip logic into the media stream
- Refactor the media stream a small bit into smaller chunks
> Fix playback get stuck when there is a stream error on a single track

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/enums.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/_template_player_provider/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos_s1/__init__.py
- music_assistant/server/providers/sonos_s1/player.py
- Use flow mode by default if device does not support enqueue next
- Remove (hacky) workaround to play next track if current track stopped playback (as alternative for no native enqueue support) - it caused too many side effects and complicated code. Just use flow mode if the device does not support enqueuing.
- Fix enqueuing of short tracks
- Fix enqueuing in case of repeat mode
- Fix current track reporting for slimproto
> Fix several issues with enqueueing of next track

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/media_items.py
- music_assistant/common/models/streamdetails.py
- music_assistant/constants.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/filesystem_local/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- Allow reading normalization tags from files
- Use gain-based correction when measurement exists, fallback to dynamic if not.
- Allow dynamic mode to be enforced for radio streams
- Use f32 in the intermediate pcm stream
- Apply limiter (just in case) at the end of the chain
> Volume normalization improvements

- music_assistant/server/providers/bluesound/__init__.py
> fixed deprecated enqueue next issue, announcements should work now too

- music_assistant/common/models/player.py
- music_assistant/common/models/queue_item.py
- music_assistant/constants.py
- music_assistant/server/controllers/player_queues.py
Change API schema a tiny bit while being compatible
- Account for updated type of loudness in streamdetails
- Mark some player attributes as optional
For now the updated values will be converted/omitted during serializing.
We can remove that code in a few weeks/months.
> Fix API compatibility

- music_assistant/server/helpers/audio.py
While UTF-8 should be the standard, apparently there are radio stations providing the streamtitle in another charset.
Fixes: https://github.com/music-assistant/hass-music-assistant/issues/2908
> Fix: Handle radio stations providing non utf-8 in streamtitle

- music_assistant/server/providers/slimproto/__init__.py
The cache keys being used for saving previous state and for loading state when connecting did not match.
> Fix loading state from cache when connecting to slimproto players

- music_assistant/common/helpers/util.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/helpers/process.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- tests/test_helpers.py
- Fix version parsing logic
- Enforce flow mode on HA players that do not support enqueuing
- enable flow mode by default on dlna
- enable http profile 2 for slimproto groups
- ignore decode errors in stderr log reading
- fix index error in queue
- fix cast child player media status
> A few small bugfixes and enhancements to playback and enqueuing 

- music_assistant/server/controllers/player_queues.py
Simple but effective change that fixes a bug where a we don't apply flow mode on a playlist even though it is enabled.
> Fix: flow mode not being applied in all cases (while it should)

- music_assistant/server/controllers/player_queues.py
Always disable shuffle in radio mode. so we keep our fancy radio pattern of songs in the queue.
> Fix: Disable shuffle for radio mode

- .pre-commit-config.yaml
- Dockerfile
- music_assistant/__main__.py
- music_assistant/common/helpers/util.py
- music_assistant/common/models/api.py
- music_assistant/common/models/event.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/api.py
- music_assistant/server/helpers/app_vars.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/images.py
- music_assistant/server/helpers/logging.py
- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/webserver.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/chromecast/helpers.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/filesystem_local/__init__.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/sonos_s1/helpers.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/server.py
- pyproject.toml
We switched to ruff for all linting/checking. Remove all (leftover) traces of pylint.
Next step: Enable the ruff rules one by one that are now temporary disabled.
> Maintenance: Replace pylint with ruff

- music_assistant/server/providers/filesystem_local/helpers.py
- tests/server/providers/filesystem/test_helpers.py
I have found this problem while investigating why some of the covers don't load for me in https://github.com/orgs/music-assistant/discussions/2976.
This fixes how the album directory is parsed when the directory name includes the version.
Prior to this patch:
```
>>> print(get_album_dir(track_dir='/media/download/others/Kiasmos - II - (WEB)', album_name="II"))
None
```
After the patch:
```
>>> print(get_album_dir(track_dir='/media/download/others/Kiasmos - II - (WEB)', album_name="II"))
/media/download/others/Kiasmos - II - (WEB)
```
> fix: album directory parsing with album versions

- music_assistant/server/providers/snapcast/__init__.py
We have a new contributor, @whc2001 thank you for your help 🎉🎉
Some configuration options and some related details are fixed.
Fixes the problem with tts cutting off in the middle of the time, but there is still a problem with very short tts, like “Hi” where it just stops the music that is playing and comes back with the music after a few seconds and you never hear the chime or the “Hi”.
> Snapcast: Add configuration options 

- music_assistant/server/providers/snapcast/__init__.py
This pull request includes a small but important change to the `cmd_volume_mute` method in the `music_assistant/server/providers/snapcast/__init__.py` file. The change ensures that the player's mute status is correctly updated in the system.
> Refactor SnapCastProvider cmd_volume_mute method

- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/playlists.py
- music_assistant/server/providers/apple_music/__init__.py
Should handle both the case of HLS radio streams and Apple Music
> Fix parsing of HLS (sub)streams

- music_assistant/common/models/player_queue.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/player_queues.py
(prevent players skipping over tracks)
> Fix track enqueuing
