music-assistant/server

- music_assistant/controllers/players.py
- music_assistant/mass.py
- music_assistant/models/player_queue.py
move streams controller to main
> Move streams controller

- music_assistant/helpers/process.py
Fix race condition where remaining write while process is already closed casued a BrokenPipe error
> Fix for BrokenPipe error

- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/stream.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/cache.py
- music_assistant/helpers/compare.py
- music_assistant/helpers/database.py
- music_assistant/mass.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
- music_assistant/providers/filesystem.py
- music_assistant/providers/qobuz.py
- music_assistant/providers/spotify/__init__.py
breaking change to make it more future proof
full db resync needed
> Fix sort order of MediaQuality

- music_assistant/helpers/compare.py
- music_assistant/helpers/util.py
- tests/utils.py
perform check for explicit/non explicit
fix bug in logic that parses version from title string
> Fix version parsing in track matching logic

- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/util.py
- music_assistant/models/media_items.py
- music_assistant/providers/filesystem.py
- music_assistant/providers/qobuz.py
- music_assistant/providers/spotify/__init__.py
- music_assistant/providers/tunein.py
Create unique id for each file in db
Handle usecases of file move and remove actions
Prevent duplicate tracks being added
Enforce uniqueness of provider ids
> Improve filesystem music provider

- music_assistant/controllers/stream.py
- music_assistant/helpers/images.py
some leftover after metadata refactor
> Fix image lookups

- examples/full.py
- music_assistant/controllers/players.py
- music_assistant/controllers/stream.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/database.py
- music_assistant/models/player.py
- music_assistant/models/player_queue.py
- easier save/restore of player preferences
- future proofing
- handle stream transcoding based on player capabilities
> Refactor queue settings

- music_assistant/models/player_queue.py
> Do not send full queue object if only the time changed

- music_assistant/controllers/stream.py
- music_assistant/helpers/util.py
- music_assistant/mass.py
Auto select free port if the default port 8095 is already taken.
Fixes https://github.com/music-assistant/hass-music-assistant/issues/63
> Auto select stream port if 8095 is taken

- music_assistant/helpers/database.py
table exists check is flaky on sqlite, work around it
> Fix TypeError in initial database setup

- music_assistant/providers/tunein.py
- respect sort order
- support library folders
> Improve Tunein music provider

- music_assistant/helpers/util.py
makes it easier to open up network ports etc
> Select stream port from predefined range

- examples/full.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
To quickly get total number of library items
> Add count helper functions

- music_assistant/controllers/music/radio.py
- music_assistant/helpers/cache.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
- music_assistant/providers/tunein.py
- fix playback of Tune In radio streams
- fix support for old style favorites (instead of the new library system)
- support subfolders in library hierarchy
> Fix Tune-In Radio playback

- music_assistant/helpers/compare.py
Track compare can potentially have ItemMapping attached for album, handle that
> Fix error in compare track utility

- music_assistant/models/player_queue.py
In preparation of new contextvar in Home Assistant
> Add passive mode to play_media

- music_assistant/controllers/music/albums.py
- music_assistant/helpers/cache.py
- music_assistant/helpers/database.py
- music_assistant/models/media_items.py
- music_assistant/providers/filesystem.py
Small refactor of the filesystem provider
- better handling of partial or missing ID3 tags
- fallback to filename 
- support for deep structure artist/album/track and loose structure where the music files are just dumped in a folder
> Improve filesystem provider

- music_assistant/models/enums.py
- music_assistant/models/player.py
- music_assistant/models/player_queue.py
Add support for playback of m4a audio files
> Add support for m4a audio container

- music_assistant/controllers/metadata/audiodb.py
- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/tracks.py
- music_assistant/controllers/stream.py
- music_assistant/helpers/audio.py
- music_assistant/helpers/compare.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
- music_assistant/models/player_queue.py
- music_assistant/providers/filesystem.py
- music_assistant/providers/qobuz.py
- music_assistant/providers/spotify/__init__.py
- pylintrc
- setup.cfg
fix issues and speedup of the filesystem provider
> Improve filesystem sync

- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/controllers/music/tracks.py
- music_assistant/controllers/stream.py
- music_assistant/helpers/compare.py
Always prefer ID3 tags for album and albumartist and use foldernames only as fallback and for additional metadata.
Discussed in https://github.com/music-assistant/hass-music-assistant/issues/165
> Prefer ID3 tags for filesystem provider

- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
Cleanup database when item gets deleted from disk
> Add support for removal of items to filesystem

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/compare.py
The matching logic had a few flaws causing tracks from different versions to be matched on the filesystem provider.
This got unnoticed before due to testing with streaming providers (which have isrc on track level).
With this change a track is only considered the same if the following conditions match:
isrc or MusicBrainsRecordId match
OR:
- Artist(s) match
- Duration match
- Version match
- Explicit yes/no match (if present in metadata)
- Album match if albumtype album/single OR both albums are various artists compilation albums
Tested this with a collection test files and seems to work perfectly fine now. Also tested with filesystem only scenario just to be sure.
Should fix https://github.com/music-assistant/hass-music-assistant/issues/184
> Make matching logic for tracks more strict

- music_assistant/controllers/metadata/musicbrainz.py
The MusicBrainz artist id lookup was a bit too strict and missing cases where the artistname does not include 'The' or other prefixes. (e.g. 'The Beatles' vs 'Beatles').
> Fix musicbrainz artist id lookup

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/database.py
- music_assistant/models/media_items.py
apparently they got lost somewhere in the refactor last week.
> Fix missing disc and track number in db

- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/cache.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
- music_assistant/models/provider.py
Save a bit of overhead in various database transactions
> Optimize database transactions

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/helpers/database.py
As discussed in https://github.com/music-assistant/hass-music-assistant/issues/184
> Fix AlbumType detection

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
Some optimizations in the datamodel and added indexes
> Optimize database for large collections

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/tracks.py
Improve the matching/linking logic that connects an item on different providers
> Improve match/link logic

- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/providers/filesystem.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/compare.py
- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
- Parse artist/title from filename if ID3 tags missing/incomplete
- Better logging of parse failures
- Make file extension case insensitive
- Handle deletion of file provider or change of folder
- Fix relative paths in playlists
> Improve parsing of metadata in fileprovider

- music_assistant/controllers/music/providers/filesystem.py
Fix for case-sensitive issue when resolving contenttype from file extension on playback
> Fix for case-sensitive contenttype from file extension

- music_assistant/models/player.py
- music_assistant/models/player_queue.py
fixes https://github.com/music-assistant/hass-music-assistant/issues/269
> Derive stream contenttype from grouped player childs

- music_assistant/controllers/stream.py
- music_assistant/models/enums.py
- music_assistant/models/player_queue.py
- music_assistant/models/queue_item.py
Fix playback of provided plain url such as radio url from HA radio browser
> Fix playback of provided plain url

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
Do not timeout on the total connection but only on the retrieval of an individual chunk
> Change timeout for radio connections

- music_assistant/controllers/streams.py
- music_assistant/models/player_queue.py
- disable repeat mode while playing alerts
- chop off some silence
- always use MP3, it makes no sense to stream lossless here
> Small improvements to the announce/alert feature for TTS

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/models/media_controller.py
- music_assistant/music_providers/filesystem.py
- allow initial scan to be resumed when HA is restarted while initial scan is running
- overwrite existing metadata of album/track if ID3 tags updated
> Filesystem improvements

- music_assistant/helpers/database.py
- music_assistant/models/media_controller.py
This solves memory issues reported by people with very large libraries. Needs changes in the HA side of things too
> Implement paging on library listings

- music_assistant/music_providers/spotify.py
Fixes playback for users in some country (reported Denmark, Norway but here may be others too)
> Add workaround for spotify AP resolve issue

- music_assistant/controllers/players.py
- music_assistant/models/player_queue.py
let lib consumer handle unavailable players
> Pass unavailable players

- music_assistant/controllers/streams.py
- music_assistant/helpers/process.py
Increase the buffer a tiny bit to optimize radio streams
> Increase buffer size for radio streams

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- music_assistant/models/player_queue.py
- support sending icy metadata
- fix playback on players that do multiple GET requests (e.g. Kodi/OSMC)
> Fix playback on Kodi/OSMC

- music_assistant/music_providers/tunein.py
Tune-In has a somewhat hidden feature to add custom URL's to your library, only available from the TuneIn app.
The entire tunein music provider crashed if one of those URL's was present.
This fixes the crashing and even adds support for playing those custom urls.
> Fix for custom URL(s) in Tune-In Library

- music_assistant/controllers/streams.py
- music_assistant/models/player_queue.py
- another fix for reconnecting Kodi players
- fix for passive playback start
> Some small fixes

- music_assistant/controllers/players.py
- music_assistant/models/player.py
- music_assistant/models/player_queue.py
move polling logic to player manager
> Centralize polling logic

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/compare.py
- music_assistant/models/media_controller.py
- music_assistant/music_providers/filesystem.py
- do not crash on single directory
- fix folder.png for albums
- overwrite existing metadata on tag changes
- keep checksum for cached listings
> Improvements for filesystem provider sync

- music_assistant/music_providers/spotify.py
Add support for Spotify playback on FreeBSD (x86-64 only)
> Add support for FreeBSD

- music_assistant/music_providers/filesystem.py
- Skip over system directories (starting with a dot), like recycle-bin folders.
- Skip subfolder if it can't be enumerated
> Skip system directories (like recycle) in the filesystem scan

- music_assistant/helpers/audio.py
- music_assistant/models/media_items.py
- music_assistant/models/player_queue.py
- music_assistant/music_providers/filesystem.py
- music_assistant/music_providers/qobuz.py
- music_assistant/music_providers/url.py
- music_assistant/music_providers/ytmusic/ytmusic.py
Minimize overhead by allowing ffmpeg to consume the file/url directly.
Also fixes seek on Youtube provider
> Use direct stream whenever possible to minimize overhead 

- music_assistant/music_providers/ytmusic/ytmusic.py
This PR:
- Adds caching of signature Timestamps and ciphers to improve playback speed
- Fixes albums sometimes not loading
- Adds `expires`, `sample_rate` and `channels` to streamdetails
> Improve Youtube Music

- music_assistant/music_providers/ytmusic/ytmusic.py
so the contents can be refreshed
> Set checksum on YTM playlist

- music_assistant/controllers/metadata/__init__.py
- music_assistant/controllers/music/__init__.py
- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/uri.py
- music_assistant/models/media_controller.py
- music_assistant/models/music_provider.py
- music_assistant/music_providers/filesystem.py
- fix coverart on tracks
- if ID3 tags are changed by user, force overwrite of info in db
- optimize file deletions
- fix musicbrainz albumartistid parse from id3 tags
- make platlist parsing more robust
- require track duration
> Various fixes for filesystem provider

- music_assistant/music_providers/ytmusic/helpers.py
- music_assistant/music_providers/ytmusic/ytmusic.py
Fixes [`error 'duration_seconds' in Library sync for Youtube Music`](https://github.com/music-assistant/hass-music-assistant/issues/669)
> Fix playlist checksum

- music_assistant/music_providers/filesystem.py
- fix typo of path
- remove all the redundant code
> Fix deleted files logic

- music_assistant/helpers/tags.py
- music_assistant/models/player_queue.py
- [fix artist splitter](https://github.com/music-assistant/music-assistant-lib/commit/87710e36eac480449e9712af1fa26d2bbd1a7cd3)
- [fix repeat](https://github.com/music-assistant/music-assistant-lib/commit/406145a8a5d4bfda83caed4a5aa3216572ebf151)
- [fix add to queue when shuffle is enabled](https://github.com/music-assistant/music-assistant-lib/commit/4c637a3866f47607d45df887f6c5271a88c47f7a)
> A few small fixes

- music_assistant/controllers/music/albums.py
- music_assistant/controllers/music/artists.py
- music_assistant/controllers/music/playlists.py
- music_assistant/controllers/music/radio.py
- music_assistant/controllers/music/tracks.py
- music_assistant/helpers/compare.py
- music_assistant/models/media_controller.py
- music_assistant/models/media_items.py
- music_assistant/models/player_queue.py
- make the album/track versions lookup a bit more strict
- ignore MediaNotFoundError when recursively deleting items from the db
- fix refresh overwriting local metadata
- allow resume of non-MA sources
- fix race condition in announcements playback
> A few small usability fixes

- music_assistant/constants.py
- music_assistant/controllers/streams.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/802
> A way to override base_url (#802)

- music_assistant/music_providers/filesystem/filesystem.py
fixes https://github.com/music-assistant/hass-music-assistant/issues/755
> Fix: filesystem browse ignoring case

- music_assistant/music_providers/ytmusic/ytmusic.py
This PR removes additional search API calls and enhances the parse-functions to deal with the sad search results coming from YT Music.
> Improve performance of YT Music search

- music_assistant/controllers/streams.py
- music_assistant/helpers/audio.py
- music_assistant/mass.py
- music_assistant/music_providers/qobuz/qobuz.py
Hopefully this fixes the dreaded issue that Qobuz streams sometimes get aborted halfway through a song.
In any way the logging has been improved to better diagnose if there may still be issues.
> Fix Qobuz media stream gets aborted

- music_assistant/music_providers/ytmusic/ytmusic.py
Some countries do not currently support youtube music. I tried using YTM_DOMAIN which is https://www.youtube.com, it works fine
> Fix Youtube Music support for some countries

- music_assistant/server/providers/frontend/manifest.json
- requirements_all.txt
https://github.com/music-assistant/frontend/releases/tag/20230310.0
> Bump frontend to 20230310.0

- README.md
> Fix 2 typos 

- .github/workflows/test.yml
- music_assistant/server/helpers/compare.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_smb/manifest.json
Fix some issues with parsing tags (e.g. duration) from the SMB music provider and set some other defaults
> Fix parsing tags from smb provider

- music_assistant/common/models/config_entries.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- [add some guards for missing metadata in cast](https://github.com/music-assistant/server/commit/993e17d1f905bdbd21912df84fc9ffa0166e9341)
- [only restart airplay bridge if needed](https://github.com/music-assistant/server/commit/f2b038896a6cfc5b980400cd8465e629a72b4938)
- [add more guards for unavailable providers](https://github.com/music-assistant/server/commit/452f52c8c7bd15b330a095ccc10da3bfd1ac96c0)
> Some small bugfixes and improvements

- DEVELOPMENT.md
This PR adds
* A template / structure for dev docs.
* Content of setting up a local dev env.
> Add setting up local dev env docs

- music_assistant/common/models/queue_item.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/didl_lite.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/json_rpc/models.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/__init__.py
Resolve queue item image url (use image proxy) so players can also display embedded covers
> Fix image of queue item if source is file based

- music_assistant/common/helpers/uri.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/music.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/json_rpc/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
Some backend changes to complement the Search and Browse features in the frontend
> Fixes for Browse and Search features

- music_assistant/server/providers/ytmusic/helpers.py
Fix playlist only loading 100 songs max
> Fix playlist max 100 songs

- music_assistant/common/models/config_entries.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/radio.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/models/metadata_provider.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_local/helpers.py
- music_assistant/server/providers/filesystem_local/manifest.json
- music_assistant/server/providers/filesystem_smb/manifest.json
- music_assistant/server/providers/lms_cli/models.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
@marcelveldt
[add guard for empty objects](https://github.com/music-assistant/server/pull/551/commits/a43c51b39a766769c45fbdffebccc3b44fb0eaa1)
[a43c51b](https://github.com/music-assistant/server/pull/551/commits/a43c51b39a766769c45fbdffebccc3b44fb0eaa1)
@marcelveldt
[better handle value type conversions](https://github.com/music-assistant/server/pull/551/commits/5566338577d70a19c0e27329aa1173526de1bb51)
[5566338](https://github.com/music-assistant/server/pull/551/commits/5566338577d70a19c0e27329aa1173526de1bb51)
@marcelveldt
[set playlist author for YTM](https://github.com/music-assistant/server/pull/551/commits/5265b01dd00fc1f644984e8dcfbbfddfefd87877)
[5265b01](https://github.com/music-assistant/server/pull/551/commits/5265b01dd00fc1f644984e8dcfbbfddfefd87877)
@marcelveldt
[typo in …
> Various small fixes and improvements

- music_assistant/common/models/enums.py
- music_assistant/common/models/media_items.py
- music_assistant/constants.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/radio.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/compare.py
- music_assistant/server/helpers/images.py
- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_local/helpers.py
- music_assistant/server/providers/musicbrainz/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
- pyproject.toml
- requirements_all.txt
- Improve parsing tags for the filesystem providers
- Handle various edge cases
- Fix local artwork
> Improve tag and matching logic

- music_assistant/server/helpers/didl_lite.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/url/__init__.py
Some radio stations (e.g. BBC) have switched to mpeg dash broadcasts, this is now fixed.
> Fix radio streams

- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- Fix images
- Ignore invalid paths
- Better error messages
- Add connection limit
> Various optimizations for file/smb provider

- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/helpers/util.py
Race condition when Iterator was exited before continuing was leaving sockets open.
> Fix system lockup caused by SMB Provider

- music_assistant/server/providers/ytmusic/helpers.py
This PR fixes a search error in YTM by adding the 8790248129038211th way of parsing an API result.
> Fix search of artist in YTM.

- music_assistant/server/providers/ytmusic/__init__.py
Fix retry of stream url after expired cipher.
> Fix await stream url.

- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/server.py
Better handling of media that is (temporary) not available on a provider, especially on streaming providers that like to change the id's of items.
> Handle unavailable media

- music_assistant/server/providers/tidal/manifest.json
> Update link to Tidal documentation

- music_assistant/server/providers/tidal/__init__.py
As MA handles unavailable tracks very well, I am adding them to the parsed responses for albums, similar tracks, artists top tracks, so that the user has an overview of this.
> include tracks that are not available currently

- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
Fix playlist edit in deezer provider
This also uses deezer-python from pypi instead of my git repo
> Fix playlist edit Deezer

- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/helpers.py
- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
This PR fixes various YTM bugs:
- (Hopefully) MediaNotFound bug
- 'Your likes' for multiple users: https://github.com/music-assistant/hass-music-assistant/issues/1126
- (Hopefully) 401: Unauthorized for artists: https://github.com/music-assistant/hass-music-assistant/issues/1203
> Fix various YT Music bugs

- music_assistant/server/controllers/media/albums.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tidal/helpers.py
1. Added availability to tidal album provider mappings.
2. Added lots of exception handling
3. Ignore unavailable albums when pre-caching tracks in albums.py
> Add availability to tidal album provider mapping

- music_assistant/server/providers/deezer/__init__.py
Stop checking multiple times if a track is available in the user country
> [Deezer] Optimizations: Stop checking if track is available all the time

- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
> Bump deezer-python to 5.12.0

- music_assistant/server/helpers/audio.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/deezer/gw_client.py
- music_assistant/server/providers/deezer/helpers.py
- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
- Adds `fd` to whitelisted protocols
- Adds documentation to manifest
- Updates throttler limits
- Stop using eval to convert to int
- Names the provider based on Deezer username
- Adds limit parameter to get_artist_top function
> [Deezer] Quality of life and refactor

- music_assistant/server/providers/slimproto/manifest.json
- requirements_all.txt
Fixes the missing font directory
> Bump aioslimproto to 2.3.1

- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/slimproto/cli.py
Fixes https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=30383644
> Fix sync of slimproto/airplay players

- music_assistant/common/helpers/util.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- music_assistant/server/providers/ugp/manifest.json
breaking change: universal player groups need to be recreated after this PR and will be configured within a single instance of the universal group player provider
> Fix several issues with  Universal Player Group provider

- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/helpers.py
This PR:
- Changes the radio endpoint
- Fixes OAuth issues
> Change radio endpoint + oauth fixes

- music_assistant/server/providers/ytmusic/__init__.py
Create new cipher on invalid playback url
> Create new cipher on invalid playback url

- music_assistant/server/providers/slimproto/cli.py
- music_assistant/server/providers/slimproto/models.py
Fix metadata (player status command) on Telnet CLI which is used by the Airplay hook on slimproto
> Fix metadata on airplay

- music_assistant/server/controllers/metadata.py
- music_assistant/server/helpers/images.py
- music_assistant/server/providers/filesystem_local/base.py
- pyproject.toml
- requirements_all.txt
- [Support m3u8 playlists in file providers](https://github.com/music-assistant/server/pull/721/commits/6ff2e64c51020592cfc0c9093cca93d1395e3c96)
- [Fix creating collage/thumbnail for local playlists](https://github.com/music-assistant/server/pull/721/commits/b40f93909e70cc810a8da3bb5e6bd47e242ebdc4)
- [bump frontend to 20230616.0](https://github.com/music-assistant/server/pull/721/commits/e77b40e69627e4f30f6051ce87606ee568733d3f)
- [support relative filenames in playlists](https://github.com/music-assistant/server/pull/721/commits/8e80bc85e1f2334708b9f49ae098052ae3516159)
> Some small fixes and improvements

- music_assistant/server/providers/ytmusic/__init__.py
This PR fixes personal playlists for multiple instances.
> Fix personal playlists for multiple instances.

- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/helpers.py
- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
This PR:
- Fixes pytube not finding throttling function
- Streamline 'get_song'
> Fix pytube not matching function name.

- music_assistant/server/providers/tidal/manifest.json
- requirements_all.txt
Fix for the recent tidalapi change
> Fix tidal issue with 'gender'

- music_assistant/server/providers/ytmusic/__init__.py
Make sure oauth token is valid upon requesting stream details
> Add oauth check to get_stream_details

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/enums.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/util.py
- music_assistant/server/models/core_controller.py
- music_assistant/server/providers/chromecast/__init__.py
- pyproject.toml
- requirements_all.txt
- Load builtin webserver on the correct (internal) network
- Make webserver configuration possible from the frontend (e.g. bind ports etc)
> Fix webserver configuration

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/player.py
- music_assistant/server/controllers/players.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- feature to use mute as power control for child players
- better handling of clients powering on/off
> Various improvements to the Universal Player Group

- music_assistant/server/providers/ugp/__init__.py
Fix error in universal group player introduced by the the new mute feature
> Fix error in Universal group player

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/enums.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/providers/slimproto/models.py
- music_assistant/server/providers/ugp/__init__.py
Some follow-up improvements for the child muting feature after testing it a while
> Improve Universal Group Player mute feature

- .github/workflows/release.yml
- Dockerfile
also switch to jemalloc for better memory management
> Fix including the correct version number into the final docker image

- music_assistant/server/providers/dlna/__init__.py
to debug some issues that have been reported
> Add verbose logging to dlna provider

- music_assistant/__main__.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/logging.py
- music_assistant/server/models/provider.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/server.py
- pyproject.toml
- requirements_all.txt
restructure all logging handling throughout the application
> Fix logging

- music_assistant/client/client.py
- music_assistant/constants.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/api.py
- music_assistant/server/helpers/database.py
- music_assistant/server/helpers/webserver.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/server.py
Fix playback issues for cast and dlna players
> Fix Playback issues on cast and dlna players

- music_assistant/server/providers/sonos/__init__.py
To allow coextsitence with HA on the same host
> Change default Sonos callback port

- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
> Bump ytmusicapi to 1.1.1

- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tidal/manifest.json
- requirements_all.txt
Switch to "official" tidalapi from PyPi
> Tidalapi-official

- music_assistant/server/providers/deezer/__init__.py
> [Deezer] Fix parsing the tracks

- music_assistant/client/music.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/music.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/radiobrowser/__init__.py
- convert to generators (to allow large listings)
- fix translated labels
- add back path
requires new frontend
> Improve Browse feature

- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- ignore non-track items in filesystem playlists
- fix deezer playlist tracks
> Some fixes for Playlist tracks

- .github/workflows/release.yml
Hopefully this will work as expected
> add job to update addon version

- music_assistant/server/providers/deezer/__init__.py
Implements radio mode to deezer. Feature not available through offical api so had to use the GW api
> [Deezer] Implement radio mode

- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
There was a bug in the deezer-python-async lib which caused problems in specific pagination fetches (Searching). Fixed in [v0.1.1](https://github.com/music-assistant/deezer-python-async/releases/tag/v0.1.1) of the library
> [Deezer] Fix search

- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tidal/helpers.py
Fixes issue: https://github.com/music-assistant/hass-music-assistant/issues/1475
> Fix similar tracks function

- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/deezer/manifest.json
- requirements_all.txt
Fixes a bug where it throws an error if the album dosnt have a cover image
Also updates deezer-python library to match upstream
> [Deezer] Fix sync album if no cover image

- music_assistant/server/providers/tidal/__init__.py
Somehow missed the fact that I had no session object for adding or removing from library
> add missing session object to add/remove from library

- .github/workflows/release.yml
Fixes an issue where the addon will be updated with a mising/blank version
> Fix config for addon update action

- music_assistant/common/models/config_entries.py
Changes made per the discussion here https://github.com/music-assistant/hass-music-assistant/issues/1501#issuecomment-1786833914
> Adjust volume normalisation default

- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/slimproto/cli.py
- music_assistant/server/providers/slimproto/models.py
- Add a few missing properties to the slimproto cli
- Handle request for repeat and shuffle status
Fixes streaming for WiiM Pro streamers running squeezelite
> Fixes for slimproto cli and wiim pro streamers

- music_assistant/constants.py
- music_assistant/server/controllers/music.py
- music_assistant/server/providers/musicbrainz/__init__.py
Fix some small db migration issues introduced in schema 26 (beta 76)
> Follow-up fix for db migration issue

- pyproject.toml
Revert to previously formatted layout
> Fixing pyproject.toml

- music_assistant/server/providers/sonos/manifest.json
- music_assistant/server/providers/tunein/manifest.json
- music_assistant/server/providers/ugp/manifest.json
Add doc link for universal group
> Update manifest files for several providers

- music_assistant/server/providers/url/__init__.py
I’m not sure if there is a downside to retaining the extra info but we have two open issues which will be resolved if we do so…?
> Retain extra url keys

- music_assistant/common/models/media_items.py
A few small tweaks to the models to prevent errors when mbid is accessed on an ItemMapping object
> Some tweaks to MediaItem models

- music_assistant/server/providers/snapcast/__init__.py
Also note that the user can change the default snapcast configuration, causing it to malfunction. 
Add prefix to dynamically created streams.
> Fixes bug where sanpcast does not work

- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
Reverting a change in the ytmusicapi that currently breaks YTMusic.
> Reverting a change in the ytmusicapi that currently breaks YTMusic.

- music_assistant/common/helpers/util.py
- music_assistant/common/models/media_items.py
- music_assistant/server/helpers/util.py
Replace to check if a musicbrainz id is valid by a more robust one
> Replace UUID check on MusicBrainz ID

- music_assistant/server/providers/ytmusic/helpers.py
- music_assistant/server/providers/ytmusic/manifest.json
- requirements_all.txt
This PR:
- Fixes https://github.com/music-assistant/hass-music-assistant/issues/1710
- Bumps ytmusicapi to a version that is compatible with our OAuth
> Youtube maintenance

- music_assistant/constants.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/chromecast/__init__.py
1) Remove the "alternative app" option from the player settings. It doesnt really bring anything to the table other than playback issues,
2) Add a small workaround so that the (physical) next button will work on cast players, as well as asking google home to play the next track by voice. The next track button is however still not displayed on the nest hub, not sure why that is.
> A few small improvements to the Chromecast provider

- music_assistant/server/providers/opensubsonic/manifest.json
- music_assistant/server/providers/opensubsonic/sonic_provider.py
- requirements_all.txt
Two commits, here. The first bumps the py-opensonic library to fix the problem loading Album or Artist Info that is empty. The second scrobbles the played song when the stream completes.
> Some fixes to the Subsonic provider

- music_assistant/common/models/config_entries.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- Fix moving last played queue item to played items on chromecast
- add back flow mode to cast for gapless
- ignore non-get and range requests in streams controller
- always create unique instance id's
- Fix Chromecast stops playing
- poll unavailable players every 5 minutes
> A collection of small fixes and enhancements

- music_assistant/server/controllers/players.py
- music_assistant/server/providers/sonos/__init__.py
> A few enqueue fixes

- music_assistant/common/models/player.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos/helpers.py
- music_assistant/server/providers/sonos/manifest.json
- music_assistant/server/providers/sonos/player.py
- music_assistant/server/providers/ugp/__init__.py
- music_assistant/server/server.py
- requirements_all.txt
Fix all issues in the sonos provider
> Fix Sonos player provider

- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos/player.py
fix for corrupted config for sonos players
fix for sync on slimproto
> Bugfixes for corrupted Sonos player configs and slimproto sync

- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/database.py
- postpone vacuum if possible
- actually commit after vacuum
- add some more logging about progress
> Speed-up startup and fix clear cache

- music_assistant/client/music.py
Fixes the following issue https://github.com/music-assistant/hass-music-assistant/issues/1802
> Fix the browsing error for album tracks

- music_assistant/server/providers/opensubsonic/manifest.json
- music_assistant/server/providers/opensubsonic/sonic_provider.py
- requirements_all.txt
The two new features are implementing ARTIST_TOPTRACKS and SIMILAR_TRACKS for the provider.
Better error handling comes from a bump in the py-opensonic version to do smarter things with default values in required fields.
Finally, I have reworked the track and album scanning to only use the UNKNOWN field as a last resort and my rescanned library has far fewer tagged as UNKNOWN in both artist and album.
> Subsonic: Two new features, better error handling, and reworked album/track parsing

- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tidal/helpers.py
First attempt at fixing a bunch of typing issues
> Tidal typing

- music_assistant/server/providers/hass/__init__.py
When running the HA add-on, the config of the HA provider will be automatic
> Fix HomeAssistant provider on supervised installs

- music_assistant/server/models/provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
Fix sending commands to playing airplay target
> Airplay fixes

- music_assistant/server/providers/deezer/__init__.py
Removes the invalid async for in the enumerators. Is tested on my machine and it fixes it
Fixes https://github.com/orgs/music-assistant/discussions/1245#discussioncomment-8541857
> [Deezer]: Fix search

- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos/player.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/server.py
- pyproject.toml
Only print stack traces if debug level enabled.
Will also hide any passwords in sent commands.
> Make the logging less verbose for errors

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/controllers/webserver.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/didl_lite.py
- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/fully_kiosk/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- Refactor some logic for synced playback and group players
- Fix weird power issues with group players
- Fix universal group playback
> Group playback fixes

- music_assistant/server/helpers/audio.py
- music_assistant/server/providers/qobuz/__init__.py
the streamdetails were cached accidentally, which is not possible on qobuz
> Fix playback issues on Qobuz

- music_assistant/server/helpers/audio.py
The analyze job is tripping ffmpeg (version 5.x) on high cpu and memory if a radio stream is sent to devnull.
We got some reports of very high memory and cpu consumption after playing (multiple?) radio streams.
We don't need this job anymore anyways as we now do it on the fly while streaming audio which is much better for resources anyways. So this leftover analyzing is now removed and that saves a bunch of cpu and memory.
> Fix high memory and cpu usage from analyze jobs

- music_assistant/constants.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- fix volume difference between regular and with "pre-announce"
- fix announcements on flow based players/sessions
- fix volume increase when initial volume was really low
> Some fixes for Announcement feature

- music_assistant/common/models/enums.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/playlists.py
- music_assistant/server/helpers/process.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/url/__init__.py
- Add support for HLS (mpeg dash) streams
- Better handling of redirects and radio playlists
- Auto restart (and log!) disconnected radio stream
> Several improvements to playing radio streams

- music_assistant/server/controllers/streams.py
- music_assistant/server/providers/airplay/__init__.py
Prevent hiccups (especially when transitioning to the next track) by adding a small buffer
> Add small buffer in Airplay streaming logic 

- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/opensubsonic/manifest.json
- requirements_all.txt
closes https://github.com/music-assistant/hass-music-assistant/issues/2054
> Fix install packages using pip

- music_assistant/server/helpers/process.py
Potential fix for the high cpu usage some people reported
> Implement a safer way to deal with the buffer limit

- docker-compose.example.yml
- music_assistant/__main__.py
- music_assistant/common/models/config_entries.py
- music_assistant/constants.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/models/core_controller.py
- music_assistant/server/models/provider.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/tidal/helpers.py
- music_assistant/server/server.py
- add environment variable to set the global log level for docker users
- correctly apply the mass logger 
- fix the issue that overriding the log level on provider/core module base want working
> Fixes for logging

- music_assistant/client/players.py
- music_assistant/common/models/config_entries.py
- music_assistant/constants.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- add flexible per-player config options
- fix announcements on airplay and snapcast
> Some enhancements to the Announcement feature

- music_assistant/common/models/enums.py
- music_assistant/common/models/streamdetails.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/url/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
get rid of the direct streaming as it hides issues
> Fix streaming issues with YouTube Music

- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/process.py
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/filesystem_local/__init__.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/tunein/__init__.py
Address all other issues found in playing - also a small refactor of the process handling so it can be logged
> More fixes for playback and better logging

- music_assistant/server/providers/spotify/__init__.py
These endpoints take an array of Spotify IDs.
> Fixes Spotify API for library Add/Remove of Artist/Album/Track

- music_assistant/server/providers/spotify/__init__.py
`type=artist` needs to be a URL parameter.
> Fixes Spotify API for library Add/Remove of Artist

- music_assistant/common/helpers/uri.py
- music_assistant/common/models/enums.py
- music_assistant/common/models/player.py
- music_assistant/constants.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/didl_lite.py
- music_assistant/server/helpers/multi_client_stream.py
- music_assistant/server/helpers/webserver.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/fully_kiosk/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos/player.py
- music_assistant/server/providers/ugp/__init__.py
- music_assistant/server/server.py
Refactor of playback handling, most important to make the UGP more isolated instead of hacks all around
> Bugfixes and improvements to (universal) player groups

- music_assistant/server/controllers/players.py
- music_assistant/server/providers/chromecast/__init__.py
A few small enhancements and bugfixes based on some feedback we got.
> Announcements improvements

- music_assistant/common/models/player_queue.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/streams.py
Repeat was really broken when flow mode is in use. This is now fixed.
Should fix a few outstanding issues we got reported @OzGav
> Fix repeat when flow mode enabled

- music_assistant/common/helpers/uri.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/1453
> Fix parse error in uri parser when track in name

- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/ugp/__init__.py
- fix volume normalization edge cases with super high dynamic range tracks
- cleanup some code and add some comments
- remove the throttling towards players as it does more harm than good
- fix slimproto single track repeat with super short tracks
> A few small fixes and optimizations to playback

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/helpers/database.py
- music_assistant/server/providers/filesystem_local/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
* fix jellyfin error handling
* Prevent duplicate artists
* filter empty lines in playlists
* optimize some db queries
* fix plex fallback artist query
* skip unavailable tunein items
* fixed plex playlists not updating
* Fix unsafe db queries
* Fix issue with radiomode looping on last track
> A collection of small bugfixes

- music_assistant/server/providers/jellyfin/__init__.py
While I was setting up a test instance of Jellyfin, I spotted a few issues.
> Handle a few errors in the Jellyfin provider

- music_assistant/server/providers/jellyfin/__init__.py
Addresses (hopefully fixes) https://github.com/music-assistant/hass-music-assistant/issues/2135
> Handle missing album key in jellyfin playlist track

- music_assistant/server/providers/tidal/__init__.py
Reapply changes that were somehow overwritten recently
> Fix add to library on Tidal

- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/radio.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/helpers/compare.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/musicbrainz/__init__.py
> Fix duplicate entries in tracks and albums listings

- music_assistant/server/providers/plex/__init__.py
fixes https://github.com/music-assistant/hass-music-assistant/issues/1847
> Mark item played on Plex after playback finishes

- music_assistant/common/helpers/util.py
- music_assistant/server/helpers/audio.py
- tests/test_radio_stream_title.py
Here's an attempt at whacking the known-known moles, while likely butchering the unknown-unknown ones ☺️ 
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2136
> Fix: Sanitize radio stream title

- music_assistant/server/providers/deezer/__init__.py
Fixes Deezer album track parsing by adding required disc number
> Fix: Deezer albums

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/artists.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2231
> Fix phantom artists in library

- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/music.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- Fix for browse listings
- Fix random sort for builtin playlists
- Catch some parse errors on JellyFin
> A collection of small bugfixes and tweaks

- .github/workflows/release.yml
This should in theory work after merging the other action PRs
> Adjust release script to account for both beta and stable releases

- music_assistant/server/providers/spotify/__init__.py
`pl = create_playlist("x") # pl['owner']['id'] not my spotify id`
`In get_playlist(pl["id"]) method: playlist_obj['owner']['id']  my spotify id`
Looks to me there's a bug in the create playlist API which is returning the incorrect owner id, but needs confirmation you're seeing the same thing and not something odd with my account.
Have fixed it by munging the returned playlist data rather than just doing a get_playlist(new_playlist['id']) in create_playlist, in order to save an api call and know when it's fixed.
If it is a confirmed bug then spotify should be notified, but from what I can see from forum posts they're not speedy with responding to API issues!
> Fix owner id mismatch bug in Spotify create playlist API

- music_assistant/server/providers/filesystem_local/base.py
Remove albums and artists that are orphans
Would fix bugs https://github.com/music-assistant/hass-music-assistant/issues/2362 and https://github.com/music-assistant/hass-music-assistant/issues/2167
> Fix cleanup of orphaned artists and albums on local file provider

- music_assistant/common/models/config_entries.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/opensubsonic/sonic_provider.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- Fix configentry warning (reported for slimproto)
- Fix smb mounts with spaces in share and/or folder name
- Fixes for paged listings
> Several small bugfixes

- music_assistant/server/providers/apple_music/__init__.py
This PR:
- Fixes wrong artist on compilation albums
- Fixes error when scrolling to the bottom of a playlist
- Adds safeguards for 504 errors
- Prefers catalog info over library info for playlists
> Apple Music: Fixed lots of metadata related issues

- music_assistant/server/providers/opensubsonic/manifest.json
- music_assistant/server/providers/opensubsonic/sonic_provider.py
- requirements_all.txt
These all support or will support starring (in subsonic, favoriting in MA) so this commit extends those stars to favorites.
> Subsonic: Extend favorites to tracks, and podcast channels and episodes

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
Basically just https://github.com/music-assistant/server/pull/1352, but for Jellyfin.
> Jellyfin: Fetch favorite userdata into library

- music_assistant/server/providers/snapcast/__init__.py
Fixes the group childs function and some minor corrections due to this change
> Fix snapcast group child 

- music_assistant/server/controllers/players.py
- music_assistant/server/providers/sonos/__init__.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2244
> Fixed volume fixes

- requirements_all.txt
Reverts music-assistant/server#1341
@MarvinSchenkel
> Revert "Bump ytmusicapi from 1.7.0 to 1.7.3"

- music_assistant/common/models/enums.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
With this PR, mypy is clear for Jellyfin.
* Added missing type defs
* Switched a bunch of things like `dict[str,Any]` to types in aiojellyfin
* Fixed some missing `UniqueList`
* Simplified a few things for the sake of mypy
* Removed some unused bits
> Jellyfin: Typing improvements

- music_assistant/constants.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/database.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
Improve performance of the database queries by optimizing them and adding some extra indexes.
Tested with a big library db I got from a community member (550.000 tracks)
> Improve library performance

- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/const.py
- music_assistant/server/providers/jellyfin/manifest.json
- requirements_all.txt
This fetches `Backdrop` and `Logo`, in addition to `Primary`.
> Jellyfin: Get more artwork from the Jellyfin instance

- music_assistant/server/providers/ytmusic/helpers.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2335
> Fix playback for video based songs without artist info.

- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/providers/ytmusic/helpers.py
Update YT DLP options to improve speed for resolving stream urls.
Fixes:
- https://github.com/music-assistant/hass-music-assistant/issues/2536
- https://github.com/music-assistant/hass-music-assistant/issues/2537
> YTMusic: Update YT DLP options to improve speed for resolving stream urls

- music_assistant/server/providers/snapcast/__init__.py
Reverts music-assistant/server#1421
> Revert "Removes check for 0.27"

- music_assistant/client/client.py
- music_assistant/client/config.py
- music_assistant/client/connection.py
- music_assistant/client/music.py
- music_assistant/client/player_queues.py
- music_assistant/client/players.py
- music_assistant/common/models/api.py
I'll add it to CI separately (blocked on https://github.com/music-assistant/server/pull/1413)
> Mypy: Get mypy passing on music_assistant.client

- music_assistant/server/providers/apple_music/__init__.py
This PR:
- Fixes https://github.com/music-assistant/hass-music-assistant/issues/2431
- Fixes https://discord.com/channels/753947050995089438/1242741503642570752/1253508280802607125
> Apple Music: Fix tracks that are unavailable in the catalog + Fix tracks with no album data

- .pre-commit-config.yaml
- music_assistant/server/helpers/tags.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/jellyfin/manifest.json
- music_assistant/server/providers/jellyfin/parsers.py
- mypy.ini
- requirements_all.txt
- tests/test_tags.py
Turns on mypy on CI for tests and jellyfin.
> Run mypy on CI

- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
Carefully handle redirect from players to queue controller and vice versa while preventing an endless loop.
This solves the reported issue where (un)pause resulted in an error.
> Carefully handle redirect from players to queue controller

- music_assistant/server/providers/soundcloud/__init__.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2467
Relies on their somewhat undocumented image formats, but not a great deal else we can do I guess.
> Fetch larger version of Soundcloud artwork

- music_assistant/server/controllers/config.py
As discussed on discord, this adds a migration at start that recovers an install by dropping corrupt providers.
> Automatically repair configs broken by the last_error retry glitch

- music_assistant/server/helpers/compare.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/filesystem_local/helpers.py
Traverse the folder structure recursively to the top to determine the album folder. 
Will fallback searching in the track's folder at all times for artwork, even if that is not named the same as the album.
> Better handling of album directory for local files

- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/providers/hass/manifest.json
- requirements_all.txt
Adds in an option to disable ssl verification and has a couple of bugfixes
> Bump hass client to 1.2.0

- music_assistant/server/providers/apple_music/__init__.py
Fix albums without name. Increase cooldown periode on 504 timeout. Also add some more logging to the 504 so we can see the request that is timing out
> Apple Music: Fix albums without name, increase cooldown periode on 504 gateway timeouts.

- music_assistant/server/providers/snapcast/__init__.py
Dryout is a poorly documented function, I have suspicions that it does not work correctly with tcp streams.
It is better to ignore the state of the snap_stream and set the state by hand, this ensures that the correct song is displayed.
> Snapcast: revert dryout and set state by hand

- music_assistant/server/controllers/webserver.py
See https://github.com/music-assistant/frontend/pull/561 for more details. Fixes https://github.com/music-assistant/hass-music-assistant/issues/2477
> Add file extension for log

- .vscode/launch.json
- music_assistant/common/models/media_items.py
- music_assistant/constants.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/compare.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
- tests/server/providers/jellyfin/__snapshots__/test_parsers.ambr
- tests/server/test_compare.py
- tests/test_helpers.py
A bit of cleanup in the compare/matching logic to fix a few bugs
Add test cases for the compare actions
> Cleanup Matching logic + add tests

- music_assistant/server/providers/opensubsonic/sonic_provider.py
Navidrome does not create an artist entry for any artist that does not have an ablum credited to them. This means that for many tracks on a Various Artists album, the instance may not have artist ID's for the artist named on the track. This patch hacks around this by creating a 'fake' artist ID for them and handling it in the provider. If the ID we create conflicts with a subsonic server's ID creation scheme we can revisit.
> Subsonic: Workaround for Navidrome Various Artists track handling

- Dockerfile
Hopefully this is the place make the name change!
> Update name to clarify difference with the integration

- music_assistant/server/helpers/tags.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2656
> Guard against eyed3 misread

- music_assistant/server/controllers/music.py
Im hoping this will fix this https://github.com/music-assistant/hass-music-assistant/issues/1953
> Add limit to tracks

- music_assistant/server/providers/filesystem_local/base.py
Fairly simple correction of a typo
> Remove artist_id not album_id

- music_assistant/common/models/provider.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/compare.py
- music_assistant/server/providers/builtin/manifest.json
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/fanarttv/manifest.json
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/fully_kiosk/manifest.json
- music_assistant/server/providers/hass/manifest.json
- music_assistant/server/providers/hass_players/manifest.json
- music_assistant/server/providers/musicbrainz/manifest.json
- music_assistant/server/providers/slimproto/manifest.json
- music_assistant/server/providers/snapcast/manifest.json
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/test/manifest.json
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/theaudiodb/manifest.json
- tests/server/providers/filesystem/__init__.py
- tests/server/providers/filesystem/test_helpers.py
Improvements to metadata retrieval + more fine grained control
> Improve metadata handling

- music_assistant/client/music.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/music.py
- Prefer library items in global search
- Add option in api to return only library results
> Fixes for global search

- music_assistant/common/models/player_queue.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/airplay/__init__.py
Some previous fixes had been overwritten by a bad merge as it seems.
This restores the fixes and adds a bit of improvement on top.
> Fix AirPlay playback gets mangled up between different streams

- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/music.py
- music_assistant/server/helpers/database.py
remove all additional track provider mappings to cleanup the mess caused  by a bug that mapped the wrong track artists.
> Cleanup database from wrong matched info

- DEVELOPMENT.md
- music_assistant/server/helpers/util.py
- music_assistant/server/models/provider.py
- music_assistant/server/providers/_template_music_provider/__init__.py
- music_assistant/server/providers/_template_music_provider/icon.svg
- music_assistant/server/providers/_template_music_provider/manifest.json
- music_assistant/server/providers/_template_player_provider/__init__.py
- music_assistant/server/providers/_template_player_provider/icon.svg
- music_assistant/server/providers/_template_player_provider/manifest.json
- music_assistant/server/server.py
- requirements_all.txt
This should help new contributors get started easily.
> Add demo/template providers

- music_assistant/client/client.py
- music_assistant/common/models/media_items.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
A series of fixes to make the provider mappings more reliable.
> Fix issues with items become unavailable

- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/playlists.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/server.py
- Fix playback of PLS based radio stations
- Fix playback of HLS (radio) streams
- Fix several issues with Soundcloud provider
- Fix auto reload/retry of providers that have dependencies (e.g. HA provider)
- Be a little bit more forgiving in db migrations
> Various bugfixes and optimizations

- music_assistant/server/controllers/config.py
- music_assistant/server/models/provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/deezer/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/fanarttv/__init__.py
- music_assistant/server/providers/filesystem_smb/__init__.py
- music_assistant/server/providers/fully_kiosk/__init__.py
- music_assistant/server/providers/hass/__init__.py
- music_assistant/server/providers/jellyfin/__init__.py
- music_assistant/server/providers/musicbrainz/__init__.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/qobuz/__init__.py
- music_assistant/server/providers/radiobrowser/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/soundcloud/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/providers/theaudiodb/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- music_assistant/server/providers/ytmusic/__init__.py
- music_assistant/server/server.py
This turned out to be a bit more rabbit hole than I expected but this fixes the issue as well as couple of other mystery issues we experienced in the past.
> Fix Spotify token gets invalidated every hour

- .vscode/launch.json
- music_assistant/client/music.py
- music_assistant/common/models/enums.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/base.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/metadata.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/images.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/apple_music/__init__.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/filesystem_local/base.py
- music_assistant/server/providers/plex/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/tidal/__init__.py
- music_assistant/server/providers/tunein/__init__.py
- Cleanup redundant tables
- Enhance both library and cache database
- Fix a few queries (e.g. randomized playlists)
> Database (performance) enhancements

- music_assistant/server/models/music_provider.py
- music_assistant/server/providers/radiobrowser/__init__.py
- Fix generic browse listings for streaming providers returning too many items
- Fix RadioBrowser browse listings
- Add a bit more caching to browse listings
> Fix (radio) browse listings

- music_assistant/server/controllers/music.py
due to leftover redundant column
> Fix new playlists get corrupted

- music_assistant/server/controllers/music.py
Prevent a full reindex when upgrading from 2.1 to 2.2
> Prevent db migration when upgrading from 2.1 to 2.2

- music_assistant/server/providers/spotify/__init__.py
- Allow clear of auth
- Use lock to prevent multiple token refreshes at the exact same time
- Retry refreshing the token once if it fails
> Small improvements to the spotify token auth

- music_assistant/common/models/queue_item.py
- music_assistant/server/controllers/cache.py
- music_assistant/server/controllers/media/albums.py
- music_assistant/server/controllers/media/artists.py
- music_assistant/server/controllers/media/playlists.py
- music_assistant/server/controllers/media/radio.py
- music_assistant/server/controllers/media/tracks.py
- music_assistant/server/controllers/music.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/database.py
- music_assistant/server/helpers/throttle_retry.py
- music_assistant/server/providers/filesystem_local/helpers.py
- Fix flow stream gets lost of track when an item gets skipped
- Refresh album tracks when refreshing an album
- Small (but effective) speed tweak for database
- Bypass throttler in providers for audio streaming
- Handle Album dir with same name as artist
> A collection of small tweaks and bugfixes

- music_assistant/server/providers/sonos/__init__.py
- Better handling of disconnect/reconnect
- Better handling of current media mapping
- Add experimental feature to link with airplay player
- Some generic tweaks
> Sonos S2 provider follow-up

- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos/manifest.json
- requirements_all.txt
- Make Airplay link less intelligent (it wasn't working that great)
- Handle connection race conditions
- Some small refactoring/cleanup
> More bugfixes for the new Sonos provider

- music_assistant/server/providers/snapcast/__init__.py
Fixes an issue where the state of the snapcast player(s) does not get updated due to a race condition between the previous stream session and the current
> Fix snapcast state not updating

- music_assistant/server/helpers/audio.py
> Fix playback of HTTP sources

- music_assistant/server/controllers/player_queues.py
due to a small race condition with enqueuing
> Fix cast/dlna player stops playing after 1 or 2 tracks of a playlist

- music_assistant/server/helpers/tags.py
If the disc/track number tags are not present, try parsing them from the filename
> Try parsing track number from the filename

- music_assistant/server/controllers/cache.py
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2938
> Fix keyerror in cache autocleanup

- music_assistant/server/controllers/player_queues.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/helpers/ffmpeg.py
- music_assistant/server/helpers/util.py
- music_assistant/server/providers/spotify/__init__.py
- Should fix Spotify randomly skipping over tracks
- Should fix (or at least help debugging) the issue where playback just goes silent / gets stuck
> Fix some playback issues

- Dockerfile.base
Should we use snapcast as a package or snapcast-server ? 
snapcast includes snapclient as well.
> Snapcast update 0.29

- music_assistant/common/models/enums.py
- music_assistant/common/models/errors.py
- music_assistant/server/controllers/config.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/models/music_provider.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/_template_player_provider/__init__.py
- music_assistant/server/providers/airplay/__init__.py
- music_assistant/server/providers/bluesound/__init__.py
- music_assistant/server/providers/builtin/__init__.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/player_group/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/snapcast/__init__.py
- music_assistant/server/providers/sonos/__init__.py
- music_assistant/server/providers/sonos_s1/__init__.py
- music_assistant/server/providers/spotify/__init__.py
- music_assistant/server/server.py
Also handle all edge cases where players get disabled/removed etc.
> More playergroups improvements

- music_assistant/common/models/enums.py
- music_assistant/common/models/player_queue.py
- music_assistant/server/controllers/player_queues.py
- music_assistant/server/controllers/players.py
- music_assistant/server/controllers/streams.py
- music_assistant/server/helpers/audio.py
- music_assistant/server/models/player_provider.py
- music_assistant/server/providers/chromecast/__init__.py
- music_assistant/server/providers/dlna/__init__.py
- music_assistant/server/providers/hass_players/__init__.py
- music_assistant/server/providers/player_group/__init__.py
- music_assistant/server/providers/slimproto/__init__.py
- music_assistant/server/providers/sonos/const.py
- music_assistant/server/providers/sonos_s1/__init__.py
- fix repeat on flow mode
- fix track calculation for flow mode
- better handling of enqueue next 
- prevent enqueue next if not supported
- fix radio mode and dont stop the music
> Several improvements to the queue controller
